// ==========================================================================
// clap — single-header build. GENERATED by tools/build_single_header.py
// DO NOT EDIT. Edit src/ and rerun the script.
// ==========================================================================

/**
 * @file clap.hpp
 * @brief CLAP - C++ Command Line Argument Parser
 *
 * @details
 * CLAP is a lightweight, header-only C++ library for parsing command line arguments.
 *
 * @section Features
 * - Flags (e.g. -v, --verbose)
 * - Options with values (e.g. -o value, --output=value)
 * - Positional arguments (e.g. input files)
 * - Multi-value options (e.g. --include=dir1 --include=dir2)
 * - Required and optional arguments
 * - Default value support
 * - Automatic usage and help message generation
 *
 * @section Usage
 * Include this header and use the clap namespace to parse command line arguments.
 *
 * @author Lucas Pujol
 * @version 1.0
 */

#ifndef CLAP_HPP
#define CLAP_HPP

#include <exception>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

// ===== ClapExceptions.hpp =====
namespace clap {
    class ClapException : public std::exception {
        public:
            ClapException(const std::string& message) : _message(message) {}

            const char* what() const noexcept override {
                return _message.c_str();
            }

        private:
            std::string _message;
    };

    class UnknownArgument : public ClapException {
        public:
            UnknownArgument(const std::string& arg)
                : ClapException("Unknown argument: " + arg) {}
    };

    class MissingValue : public ClapException {
        public:
            MissingValue(const std::string& arg)
                : ClapException("Missing value for argument: " + arg) {}
    };

    class MissingRequiredArgument : public ClapException {
        public:
            MissingRequiredArgument(const std::string& arg)
                : ClapException("Missing required argument: " + arg) {}
    };

    class ConfigError : public ClapException {
        public:
            ConfigError(const std::string& msg)
                : ClapException("Configuration error: " + msg) {}
    };

    class HelpRequested : public ClapException {
        public:
            HelpRequested() : ClapException("Help requested") {}
    };

    class ParseError : public ClapException {
        public:
            ParseError(const std::string& msg)
                : ClapException("Parse error: " + msg) {}
    };

    class InvalidValue : public ClapException {
        public:
            InvalidValue(const std::string& value, const std::string& arg,
                         const std::string& type)
                : ClapException("invalid value '" + value + "' for '" + arg + "'"
                    + (type.empty() ? "" : " (expected " + type + ")")) {}
    };
}

// ===== TypeNames.hpp =====
namespace clap {
    template<typename T>
    struct TypeName {
        static constexpr std::string_view value = "unknown";
    };

    template<> struct TypeName<int>         { static constexpr std::string_view value = "int"; };
    template<> struct TypeName<float>       { static constexpr std::string_view value = "float"; };
    template<> struct TypeName<double>      { static constexpr std::string_view value = "double"; };
    template<> struct TypeName<bool>        { static constexpr std::string_view value = "bool"; };
    template<> struct TypeName<std::string> { static constexpr std::string_view value = "string"; };
}

// ===== Argument.hpp =====
namespace clap {
    class Argument {
        public:
            Argument(std::string names, std::string description)
                : _names_raw(std::move(names)),
                  _names(split(_names_raw, ',')),
                  _description(std::move(description)) {}
            virtual ~Argument() = default;

            virtual void parse(std::string_view value) = 0;
            virtual std::string_view type_name() const = 0;

            virtual bool is_set() const noexcept = 0;
            virtual bool takes_value() const noexcept = 0;
            virtual bool is_multi() const noexcept { return false; }

            // Rendered default value for help, or empty if none.
            virtual std::string default_str() const { return ""; }

            std::string_view names() const noexcept { return _names_raw; }
            std::string_view description() const noexcept { return _description; }
            virtual bool is_required() const noexcept { return _required; }

            const std::vector<std::string>& raw_names() const noexcept { return _names; }

            // Shortest registered name, preferred for the usage summary (e.g. "-v").
            std::string_view primary_name() const noexcept {
                std::string_view best;
                for (const auto& n : _names)
                    if (best.empty() || n.size() < best.size())
                        best = n;
                return best;
            }

            bool matches(std::string_view name) const {
                for (const auto& arg_name : _names) {
                    if (arg_name == name)
                        return true;
                }
                return false;
            }

        protected:
            void set_required() noexcept { _required = true; }

        private:
            std::string _names_raw;
            std::vector<std::string> _names;
            std::string _description;
            bool _required = false;

            static std::vector<std::string> split(const std::string &str, char delimiter) {
                std::vector<std::string> tokens;
                std::istringstream iss(str);
                std::string token;

                while (std::getline(iss, token, delimiter)) {
                    token.erase(0, token.find_first_not_of(" \t\n\r\f\v"));
                    token.erase(token.find_last_not_of(" \t\n\r\f\v") + 1);
                    if (!token.empty())
                        tokens.push_back(token);
                }
                return tokens;
            }
    };
}

// ===== ArgCursor.hpp =====
namespace clap {
    class ArgCursor {
        public:
            ArgCursor(int argc, char** argv) noexcept
                : _argc(argc), _argv(argv), _pos(1) {}

            bool has_next() const noexcept { return _pos < _argc; }

            // next token without moving. precondition: has_next().
            std::string_view peek() const noexcept { return _argv[_pos]; }

            // next token, then advance. precondition: has_next().
            std::string_view next() noexcept { return _argv[_pos++]; }

            bool next_is_value() const noexcept {
                return has_next() && (peek().empty() || peek().front() != '-');
            }

        private:
            int _argc;
            char** _argv;
            int _pos;
    };
}

// ===== ParseValue.hpp =====
namespace clap {
    template<typename T>
    struct ParseValue {
        static T parse(std::string_view str) {
            std::istringstream iss{std::string(str)};
            T val;
            if (!(iss >> val) || !iss.eof())
                throw clap::ParseError("Failed to parse value");
            return val;
        }
    };

    template<>
    struct ParseValue<std::string> {
        static std::string parse(std::string_view str) {
            return std::string(str);
        }
    };

    template<typename T>
    T parse_checked(std::string_view value, std::string_view name, std::string_view type) {
        try {
            return ParseValue<T>::parse(value);
        } catch (const clap::ParseError&) {
            throw clap::InvalidValue(std::string(value), std::string(name), std::string(type));
        }
    }
}

// ===== Flag.hpp =====
namespace clap {
    class Flag : public Argument {
        public:
            Flag(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            operator bool() const noexcept { return _value; }

            void parse(std::string_view) override { _value = true; }
            std::string_view type_name() const override { return ""; }

            bool is_set() const noexcept override { return _value; }
            bool takes_value() const noexcept override { return false; }

        private:
            bool _value = false;
    };
}

// ===== Option.hpp =====
namespace clap {
    template<typename T>
    class Option : public Argument {
        public:
            Option(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            void parse(std::string_view value) override {
                _value = clap::parse_checked<T>(value, names(), type_name());
            }

            std::string_view type_name() const override {
                return clap::TypeName<T>::value;
            }
            bool is_set() const noexcept override { return _value.has_value(); }

            Option<T>& required() {
                if (_default_value.has_value())
                    throw clap::ConfigError("cannot combine required() with default_value()");
                set_required();
                return *this;
            }

            bool takes_value() const noexcept override { return true; }

            std::string default_str() const override {
                if (!_default_value.has_value()) return "";
                std::ostringstream oss;
                oss << _default_value.value();
                return oss.str();
            }

            Option<T>& default_value(T val) {
                if (is_required())
                    throw clap::ConfigError("cannot combine default_value() with required()");
                _default_value = std::move(val);
                return *this;
            }

            const T& get() const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                throw clap::MissingValue(std::string(names()));
            }

        private:
            std::optional<T> _value;
            std::optional<T> _default_value;
    };
}

// ===== MultiOption.hpp =====
namespace clap {
    template<typename T>
    class MultiOption : public Argument {
    public:
        MultiOption(std::string names, std::string description)
        : Argument(std::move(names), std::move(description)) {}

        void parse(std::string_view value) override {
            _values.push_back(clap::parse_checked<T>(value, names(), type_name()));
        }

        std::string_view type_name() const override {
            return clap::TypeName<T>::value;
        }

        bool is_set() const noexcept override { return !_values.empty(); }
        bool takes_value() const noexcept override { return true; }
        bool is_multi() const noexcept override { return true; }

        MultiOption<T>& required() {
            set_required();
            return *this;
        }

        const std::vector<T>& get() const {
            if (_values.empty())
                throw clap::MissingValue(std::string(names()));
            return _values;
        }

    private:
        std::vector<T> _values;
    };
}

// ===== Positional.hpp =====
namespace clap {
    template<typename T>
    class Positional : public Argument {
        public:
            Positional(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            void parse(std::string_view value) override {
                _value = clap::parse_checked<T>(value, names(), type_name());
            }

            std::string_view type_name() const override {
                return clap::TypeName<T>::value;
            }

            bool is_set() const noexcept override { return _value.has_value(); }
            bool takes_value() const noexcept override { return true; }

            bool is_required() const noexcept override { return !_default_value.has_value(); }

            Positional<T>& default_value(T val) {
                _default_value = std::move(val);
                return *this;
            }

            std::string default_str() const override {
                if (!_default_value.has_value()) return "";
                std::ostringstream oss;
                oss << _default_value.value();
                return oss.str();
            }

            const T &get() const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                throw clap::MissingValue(std::string(names()));
            }

        private:
            std::optional<T> _value;
            std::optional<T> _default_value;
    };
}

// ===== HelpFormatter.hpp =====
namespace clap {
    class Argument;

    class HelpFormatter {
        public:
            using ArgList = std::vector<std::unique_ptr<Argument>>;

            HelpFormatter(std::string_view name, std::string_view description,
                          const ArgList& options, const ArgList& positionals)
                : _name(name), _description(description),
                  _options(options), _positionals(positionals) {}

            std::string usage() const;
            std::string help() const;

        private:
            std::string usage_token(const Argument& arg, bool positional) const;
            std::string prefix(const Argument& arg) const;
            std::string annotation(const Argument& arg) const;
            size_t column_width() const;

            std::string_view _name;
            std::string_view _description;
            const ArgList& _options;
            const ArgList& _positionals;
    };
}

// ===== App.hpp =====
namespace clap {
    class ArgCursor;

    class App {
        public:
            App(std::string name, std::string description);

            App(const App&) = delete;
            App& operator=(const App&) = delete;
            App(App&&) = delete;
            App& operator=(App&&) = delete;

            template<typename T>
            Option<T>& option(std::string names, std::string description) {
                auto option = std::make_unique<Option<T>>(std::move(names), std::move(description));
                auto &ref = *option;
                add_argument(std::move(option));
                return ref;
            }

            Flag& flag(std::string names, std::string description) {
                auto flag = std::make_unique<Flag>(std::move(names), std::move(description));
                auto &ref = *flag;
                add_argument(std::move(flag));
                return ref;
            }

            template<typename T>
            MultiOption<T>& multi_option(std::string names, std::string description) {
                auto opt = std::make_unique<MultiOption<T>>(std::move(names), std::move(description));
                auto& ref = *opt;
                add_argument(std::move(opt));
                return ref;
            }

            template<typename T>
            Positional<T>& positional(std::string name, std::string description) {
                auto pos = std::make_unique<Positional<T>>(std::move(name), std::move(description));
                auto &ref = *pos;
                _positionals.push_back(std::move(pos));
                return ref;
            }

            void parse(int argc, char **argv);
            std::string usage() const;

        private:
            std::string _name;
            std::string _description;
            std::vector<std::unique_ptr<Argument>> _arguments;
            std::vector<std::unique_ptr<Argument>> _positionals;
            size_t _positional_idx = 0;
            Flag* _help = nullptr;

            void add_argument(std::unique_ptr<Argument> arg);
            Argument* find_argument(std::string_view name);
            static bool starts_with(std::string_view str, std::string_view prefix);

            void handle_positional(std::string_view token);
            void parse_long_equals(std::string_view token);
            void parse_short_cluster(std::string_view token, ArgCursor& cursor);
            void parse_single(std::string_view token, ArgCursor& cursor);
            void check_required() const;

            void print_help() const;
    };
}

#endif // CLAP_HPP

#ifdef CLAP_IMPLEMENTATION

#include <algorithm>
#include <iomanip>
#include <iostream>

// ===== HelpFormatter.cpp =====
std::string clap::HelpFormatter::usage_token(const clap::Argument& arg, bool positional) const {
    if (positional) {
        std::string core = "<" + std::string(arg.names()) + ">";
        return arg.is_required() ? core : "[" + core + "]";
    }
    if (!arg.takes_value())
        return "[" + std::string(arg.primary_name()) + "]";

    std::string core = std::string(arg.primary_name()) + " <" + std::string(arg.type_name()) + ">";
    std::string tail = arg.is_multi() ? "..." : "";
    return arg.is_required() ? core + tail : "[" + core + "]" + tail;
}

std::string clap::HelpFormatter::prefix(const clap::Argument& arg) const {
    std::ostringstream oss;
    oss << "  " << arg.names();
    if (!arg.type_name().empty())
        oss << " <" << arg.type_name() << ">";
    if (arg.is_multi())
        oss << "...";
    return oss.str();
}

std::string clap::HelpFormatter::annotation(const clap::Argument& arg) const {
    if (arg.is_required())
        return " (required)";
    if (!arg.default_str().empty())
        return " (default: " + arg.default_str() + ")";
    return "";
}

size_t clap::HelpFormatter::column_width() const {
    size_t max_w = 0;
    for (const auto& a : _options)
        max_w = std::max(max_w, prefix(*a).size());
    for (const auto& p : _positionals)
        max_w = std::max(max_w, prefix(*p).size());
    return max_w + 2;
}

std::string clap::HelpFormatter::usage() const {
    std::ostringstream oss;
    oss << "Usage: " << _name;
    for (const auto& a : _options)
        oss << " " << usage_token(*a, false);
    for (const auto& p : _positionals)
        oss << " " << usage_token(*p, true);
    return oss.str();
}

std::string clap::HelpFormatter::help() const {
    std::ostringstream oss;
    oss << usage() << "\n\n" << _description << "\n";

    const size_t col = column_width();

    oss << "\nOptions:\n";
    for (const auto& a : _options)
        oss << std::left << std::setw(col) << prefix(*a)
            << a->description() << annotation(*a) << "\n";

    if (!_positionals.empty()) {
        oss << "\nArguments:\n";
        for (const auto& p : _positionals)
            oss << std::left << std::setw(col) << prefix(*p)
                << p->description() << annotation(*p) << "\n";
    }
    return oss.str();
}

// ===== App.cpp =====
clap::App::App(std::string name, std::string description)
    : _name(std::move(name)), _description(std::move(description)) {
    _help = &flag("-h,--help", "Show this help message");
}

void clap::App::add_argument(std::unique_ptr<Argument> arg) {
    if (arg->raw_names().empty())
        throw clap::ConfigError("argument registered with no valid name");
    for (const auto& n : arg->raw_names()) {
        if (n[0] != '-')
            throw clap::ConfigError("option name must start with '-': " + n);
        for (const auto& existing : _arguments)
            if (existing->matches(n))
                throw clap::ConfigError("duplicate option name: " + n);
    }
    _arguments.push_back(std::move(arg));
}

clap::Argument* clap::App::find_argument(std::string_view token) {
    for (auto& arg : _arguments)
        if (arg->matches(token)) return arg.get();
    return nullptr;
}

bool clap::App::starts_with(std::string_view str, std::string_view prefix) {
    return str.size() >= prefix.size() &&
        str.compare(0, prefix.size(), prefix) == 0;
}

std::string clap::App::usage() const {
    return HelpFormatter(_name, _description, _arguments, _positionals).usage();
}

void clap::App::print_help() const {
    std::cout << HelpFormatter(_name, _description, _arguments, _positionals).help();
}


void clap::App::parse(int argc, char **argv) {
    ArgCursor cursor(argc, argv);

    while (cursor.has_next()) {
        std::string_view token = cursor.next();

        if (!starts_with(token, "-"))
            handle_positional(token);
        else if (starts_with(token, "--") && token.find('=') != std::string_view::npos)
            parse_long_equals(token);
        else if (!starts_with(token, "--") && token.size() > 2)
            parse_short_cluster(token, cursor);
        else
            parse_single(token, cursor);
    }

    if (_help && *_help) {
        print_help();
        throw clap::HelpRequested();
    }

    check_required();
}

void clap::App::handle_positional(std::string_view token) {
    if (_positional_idx >= _positionals.size())
        throw clap::UnknownArgument(std::string(token));
    _positionals[_positional_idx++]->parse(token);
}

// --option=value
void clap::App::parse_long_equals(std::string_view token) {
    auto eq = token.find('=');
    auto arg_name  = token.substr(0, eq);
    auto arg_value = token.substr(eq + 1);
    auto *arg = find_argument(arg_name);
    if (!arg)
        throw clap::UnknownArgument(std::string(arg_name));
    if (!arg->takes_value())
        throw clap::ParseError("flag '" + std::string(arg_name) + "' does not take a value");
    arg->parse(arg_value);
}

// short cluster: -vf, -c10, -c-5, -vc 10
void clap::App::parse_short_cluster(std::string_view token, ArgCursor& cursor) {
    for (size_t j = 1; j < token.size(); ++j) {
        std::string short_name{'-', token[j]};
        auto *arg = find_argument(short_name);
        if (!arg)
            throw clap::UnknownArgument(short_name);
        if (arg->takes_value()) {
            auto attached = token.substr(j + 1);
            if (!attached.empty())
                arg->parse(attached);
            else if (cursor.next_is_value())
                arg->parse(cursor.next());
            else
                throw clap::MissingValue(short_name);
            return;
        }
        arg->parse("");
    }
}

void clap::App::parse_single(std::string_view token, ArgCursor& cursor) {
    auto *arg = find_argument(token);
    if (!arg)
        throw clap::UnknownArgument(std::string(token));

    if (arg->takes_value()) {
        if (!cursor.next_is_value())
            throw clap::MissingValue(std::string(token));
        arg->parse(cursor.next());
    } else {
        arg->parse("");
    }
}

void clap::App::check_required() const {
    for (const auto& arg : _arguments)
        if (arg->is_required() && !arg->is_set())
            throw clap::MissingRequiredArgument(std::string(arg->names()));
    for (const auto& pos : _positionals)
        if (pos->is_required() && !pos->is_set())
            throw clap::MissingRequiredArgument(std::string(pos->names()));
}

#endif // CLAP_IMPLEMENTATION
