// ==========================================================================
// clap — single-header build. GENERATED by tools/build_single_header.py
// DO NOT EDIT. Edit src/ and rerun the script.
// ==========================================================================

/**
 * @file clap.hpp
 * @brief CLAP - C++ Command Line Argument Parser
 *
 * @details
 * CLAP is a lightweight, header-only C++ library for parsing command line arguments.
 *
 * @section Features
 * - Flags (e.g. -v, --verbose)
 * - Options with values (e.g. -o value, --output=value)
 * - Positional arguments (e.g. input files)
 * - Multi-value options (e.g. --include=dir1 --include=dir2)
 * - Required and optional arguments
 * - Default value support
 * - Automatic usage and help message generation
 *
 * @section Usage
 * Include this header and use the clap namespace to parse command line arguments.
 *
 * @author Lucas Pujol
 * @version dev
 */

#pragma once

#define CLAP_VERSION "dev"

#include <charconv>
#include <cstdlib>
#include <exception>
#include <filesystem>
#include <functional>
#include <initializer_list>
#include <ios>
#include <istream>
#include <memory>
#include <optional>
#include <ostream>
#include <source_location>
#include <sstream>
#include <string>
#include <string_view>
#include <system_error>
#include <type_traits>
#include <utility>
#include <vector>

// ===== ClapExceptions.hpp =====
namespace clap {
    /// What kind of error App::parse() recorded. Query via App::error_kind().
    enum class ErrorKind {
        /// A token was passed that matches no registered argument.
        UnknownArgument,
        /// A value-taking argument was given no value.
        MissingValue,
        /// A flag was given a value, e.g. --verbose=1.
        UnexpectedValue,
        /// A value had the wrong format for its type.
        InvalidValue,
        /// A required argument was absent.
        MissingRequiredValue,
        /// default: no error. App::parse() returns true and App::error() is empty.
        OK,
    };

    /// Base of every clap error. Catch this to handle them all.
    class ClapException : public std::exception {
        public:
            ClapException(const std::string& message) : _message(message) {}

            const char* what() const noexcept override {
                return _message.c_str();
            }

        private:
            std::string _message;
    };

    /// Base of the errors App::parse() reports. parse() catches these internally
    /// and records them as error state, so they never escape it. They still
    /// surface from Option::get() and friends, where they mean the caller read a
    /// value that was never set.
    class ParseException : public ClapException {
        public:
            ParseException(ErrorKind kind, const std::string& message)
                : ClapException(message), _kind(kind) {}

            /// Which ErrorKind this maps to in App::error_kind().
            ErrorKind kind() const noexcept { return _kind; }

        private:
            ErrorKind _kind;
    };

    /// An argument was passed that was never registered.
    class UnknownArgument : public ParseException {
        public:
            UnknownArgument(const std::string& arg, const std::string& hint = "")
                : ParseException(ErrorKind::UnknownArgument,
                                 "Unknown argument: " + arg
                                 + (hint.empty() ? "" : "\n\t" + hint)) {}
    };

    /// A value-taking argument was given no value.
    class MissingValue : public ParseException {
        public:
            MissingValue(const std::string& arg)
                : ParseException(ErrorKind::MissingValue,
                                 "Missing value for argument: " + arg) {}
    };

    /// A flag was given a value, e.g. --verbose=1.
    class UnexpectedValue : public ParseException {
        public:
            UnexpectedValue(const std::string& arg)
                : ParseException(ErrorKind::UnexpectedValue,
                                 "flag '" + arg + "' does not take a value") {}
    };

    /// A required argument was missing.
    class MissingRequiredArgument : public ParseException {
        public:
            MissingRequiredArgument(const std::string& arg)
                : ParseException(ErrorKind::MissingRequiredValue,
                                 "Missing required argument: " + arg) {}
    };

    /// A value had the wrong format for its type.
    class InvalidValue : public ParseException {
        public:
            InvalidValue(const std::string& value, const std::string& arg,
                         const std::string& type, const std::string& hint = "")
                : ParseException(ErrorKind::InvalidValue,
                                 "invalid value '" + value + "' for '" + arg + "'"
                                 + (type.empty() ? "" : " (expected " + type + ")")
                                 + (hint.empty() ? "" : "\n\t" + hint)) {}
    };

    /// The parser was set up wrong. Thrown while registering, not while parsing,
    /// so parse() never catches it: it means the program itself is buggy.
    class ConfigError : public ClapException {
        public:
            ConfigError(const std::string& msg)
                : ClapException("Configuration error: " + msg) {}

            /// Located, clang-style:
            /// "file:line:col: error: <msg>".
            /// loc points at the caller that registered the offending argument.
            ConfigError(const std::source_location& loc, const std::string& msg)
                : ClapException("\n" + prefix(loc) + "error: " + msg) {}

            /// Redeclaration: as above, plus a "previous definition" line at prev.
            ConfigError(const std::source_location& loc, const std::string& msg,
                        const std::source_location& prev)
                : ClapException("\n" + prefix(loc) + "error: " + msg + "\n" +
                                prefix(prev) + "previous definition") {}

        private:
            static std::string prefix(const std::source_location& loc) {
                return std::string(loc.file_name()) + ":" +
                       std::to_string(loc.line()) + ":" +
                       std::to_string(loc.column()) + ": ";
            }
    };

    /// A raw value failed to parse. Internal signal from a ParseValue
    /// specialization; parse_checked() turns it into an InvalidValue.
    class ParseError : public ClapException {
        public:
            ParseError(const std::string& msg)
                : ClapException("Parse error: " + msg), _detail(msg) {}

            const std::string& detail() const noexcept { return _detail; }

        private:
            std::string _detail;
    };
}

// ===== damerau_osa.hpp =====
namespace clap {
    /// Internals. Not part of the public API; may change without notice.
    namespace detail {
        /// Edit distance between s1 and s2, counting an adjacent swap as one
        /// edit instead of two substitutions.
        int damerau_osa(const std::string& s1, const std::string& s2);

        /// The candidate closest to unknown, or "" when nothing is close enough
        /// to be worth printing. Leading dashes are ignored when comparing.
        std::string suggest(std::string_view unknown,
                            const std::vector<std::string>& candidates);
    }
}

// ===== TypeNames.hpp =====
namespace clap {
    /// Label shown for a value type in help output, e.g. "<int>".
    /// Specialize for a custom type to give it a name.
    template<typename T> struct TypeName;

    // macro to define all accepted types
    #define CLAP_TYPENAME(T, S) \
        template<> struct TypeName<T> { static constexpr std::string_view value = S; };

    // Fundamental types only. 
    // uint8_t is unsigned char, size_t is one of the unsigned types,
    // so naming both collides.
    CLAP_TYPENAME(char,                  "char")
    CLAP_TYPENAME(signed char,           "int8")
    CLAP_TYPENAME(unsigned char,         "uint8")
    CLAP_TYPENAME(short,                 "short")
    CLAP_TYPENAME(unsigned short,        "ushort")
    CLAP_TYPENAME(int,                   "int")
    CLAP_TYPENAME(unsigned,              "uint")
    CLAP_TYPENAME(long,                  "long")
    CLAP_TYPENAME(unsigned long,         "ulong")
    CLAP_TYPENAME(long long,             "llong")
    CLAP_TYPENAME(unsigned long long,    "ullong")
    CLAP_TYPENAME(float,                 "float")
    CLAP_TYPENAME(double,                "double")
    CLAP_TYPENAME(bool,                  "bool")
    CLAP_TYPENAME(std::string,           "string")
    CLAP_TYPENAME(std::filesystem::path, "path")

}

// ===== Concepts.hpp =====
namespace clap {
    /// Satisfied when T can be read from an std::istream with operator>>.
    template<typename T>
    concept StreamExtractable = requires(std::istream& is, T& v) { is >> v; };

    /// Satisfied when T can be written to an std::ostream with operator<<.
    template<typename T>
    concept StreamInsertable = requires(std::ostream& os, const T& v) { os << v; };

    /// Satisfied when T has a TypeName, so it has a label for help output.
    template<typename T>
    concept Named = requires { TypeName<T>::value; };

    /// Turns a string into a T. The customization point for value parsing:
    /// specialize this for a type that operator>> cannot handle. See
    /// examples/custom_type.
    /// Declared here so Parseable below can name it;
    /// the default parser and the built-in specializations live in
    /// ParseValue.hpp.
    template<typename T>
    struct ParseValue;

    /// Satisfied when T has a usable ParseValue: either ParseValue<T> is
    /// specialized, or T is stream-extractable via the default parser.
    template<typename T>
    concept Parseable = requires(std::string_view s) { ParseValue<T>::parse(s); };

    /// The full contract for a clap value type: parseable from a string, and
    /// printable via operator<< so its default value can appear in help output.
    template<typename T>
    concept OptionValue = Parseable<T> && StreamInsertable<T> && Named<T>;
}

// ===== Argument.hpp =====
namespace clap {
    /// Base of every argument type. Holds names and description;
    /// subclasses decide how to parse and store a value.
    class Argument {
        public:
            Argument(std::string names, std::string description)
                : _names_raw(std::move(names)),
                  _names(split(_names_raw, ',')),
                  _description(std::move(description)) {}
            virtual ~Argument() = default;

            /// Consume a raw token as this argument's value. When discard is
            /// true the token is still validated but the result is thrown away,
            /// leaving the argument unset (used by the -/flag override syntax).
            virtual void parse(std::string_view value, bool discard = false) = 0;
            /// Type label for help, e.g. "int". Empty for flags.
            virtual std::string_view type_name() const = 0;

            /// True once a value has been parsed.
            virtual bool is_set() const noexcept = 0;
            /// True if this argument consumes a value token.
            virtual bool takes_value() const noexcept = 0;
            /// True if it can be repeated to collect a list.
            virtual bool is_multi() const noexcept { return false; }

            /// Rendered default value for help, or empty if none.
            virtual std::string default_str() const { return ""; }

            /// Constraints a validator wants stated next to the description,
            /// e.g. "must exist". Empty for flags, which take no validator.
            virtual const std::vector<std::string>& hints() const {
                static const std::vector<std::string> none;
                return none;
            }

            /// Environment variable this argument falls back to, or empty.
            virtual std::string env_key() const { return ""; }
            /// Apply the env-var fallback when still unset. May throw
            virtual void resolve_env() {}

            std::string_view names() const noexcept { return _names_raw; }
            std::string_view description() const noexcept { return _description; }
            virtual bool is_required() const noexcept { return _required; }
            bool is_hidden() const noexcept { return _hidden; }

            const std::vector<std::string>& raw_names() const noexcept { return _names; }

            /// Shortest registered name, preferred for the usage summary (e.g. "-v").
            std::string_view primary_name() const noexcept {
                std::string_view best;
                for (const auto& n : _names)
                    if (best.empty() || n.size() < best.size())
                        best = n;
                return best;
            }

            /// Where this argument was registered, for diagnostics. Set by App
            /// right after construction, so it points at the caller's site.
            void set_location(const std::source_location& loc) noexcept { _loc = loc; }
            const std::source_location& location() const noexcept { return _loc; }

            /// True if token matches one of this argument's names.
            bool matches(std::string_view name) const {
                for (const auto& arg_name : _names) {
                    if (arg_name == name)
                        return true;
                }
                return false;
            }

            virtual void reset() noexcept = 0;

        protected:
            void set_required() noexcept { _required = true; }
            void set_hidden()   noexcept { _hidden   = true; }

        private:
            std::string _names_raw;
            std::vector<std::string> _names;
            std::string _description;
            bool _required = false;
            bool _hidden = false;
            std::source_location _loc{};

            static std::vector<std::string> split(const std::string &str, char delimiter) {
                std::vector<std::string> tokens;
                std::istringstream iss(str);
                std::string token;

                while (std::getline(iss, token, delimiter)) {
                    token.erase(0, token.find_first_not_of(" \t\n\r\f\v"));
                    token.erase(token.find_last_not_of(" \t\n\r\f\v") + 1);
                    if (!token.empty())
                        tokens.push_back(token);
                }
                return tokens;
            }
    };
}

// ===== ArgCursor.hpp =====
namespace clap {
    /// Walks the argument list left to right, one token at a time
    /// (skips args[0], the program name). Does not own the list.
    class ArgCursor {
        public:
            explicit ArgCursor(const std::vector<std::string>& args) noexcept
                : _args(args), _pos(1) {}

            bool has_next() const noexcept { return _pos < _args.size(); }

            /// Index of the token next() would return. Used to tag an error
            /// with the argv slot that caused it.
            size_t position() const noexcept { return _pos; }

            /// Next token without moving. Precondition: has_next().
            std::string_view peek() const noexcept { return _args[_pos]; }

            /// Next token, then advance. Precondition: has_next().
            std::string_view next() noexcept { return _args[_pos++]; }

            /// True if a next token exists and does not look like a flag.
            bool next_is_value() const noexcept {
                return has_next() && (peek().empty() || peek().front() != '-');
            }

        private:
            const std::vector<std::string>& _args;
            size_t _pos;
    };
}

// ===== ParseValue.hpp =====
namespace clap {
    /// Default parser for any type readable with operator>>.
    template<StreamExtractable T>
    struct ParseValue<T> {
        static T parse(std::string_view str) {
            T val;
            if constexpr (std::is_arithmetic_v<T> && !std::is_same_v<T, bool>) {
                auto* first = str.data();
                auto* last = str.data() + str.size();
                auto [ptr, ec] = std::from_chars(first, last, val);
                if (ec == std::errc::invalid_argument)
                    throw clap::ParseError("");
                if (ec == std::errc::result_out_of_range)
                    throw clap::ParseError("out of range");
                if (ptr != last)
                    throw clap::ParseError("");
                return val;
            } else {
                std::istringstream iss{std::string(str)};
                if (!(iss >> val) || !iss.eof())
                    throw clap::ParseError("");
                return val;
            }
        }
    };

    /// Parser for std::string: takes the token verbatim, no stream parsing
    /// (so values may contain spaces and never fail to parse).
    template<>
    struct ParseValue<std::string> {
        static std::string parse(std::string_view str) { return std::string(str); }
    };

    template<>
    struct ParseValue<std::filesystem::path> {
        static std::filesystem::path parse(std::string_view str) { return std::filesystem::path(str); }
    };

    template<>
    struct ParseValue<bool> {
        static bool parse(std::string_view str) {
            if (str == "1" || str == "true" || str == "yes" || str == "on")
                return true;
            if (str == "0" || str == "false" || str == "no" || str == "off")
                return false;
            throw ParseError("valid values: 1, true, yes, on, 0, false, no, off");
        }
    };

    /// Parser for char: the token is a single character, not a number, so
    /// `-c A` reads the letter A. signed/unsigned char keep the numeric path.
    template<>
    struct ParseValue<char> {
        static char parse(std::string_view str) {
            if (str.size() != 1)
                throw ParseError("expected a single character");
            return str[0];
        }
    };

    /// Parses value into T, turning any failure into an InvalidValue error.
    template<typename T>
    T parse_checked(std::string_view value, std::string_view name, std::string_view type) {
        try {
            return ParseValue<T>::parse(value);
        } catch (const clap::ParseError &e) {
            throw clap::InvalidValue(std::string(value), std::string(name), std::string(type), e.detail());
        } catch (const std::exception &e) {
            throw clap::InvalidValue(std::string(value), std::string(name), std::string(type), e.what());
        }
    }
}

// ===== Validators.hpp =====
namespace clap {
    /// Builtin validators. Each is a callable that takes a value and returns an
    /// empty string on success or an error message on failure. Each also has
    /// optional members label() and hint() that describe the constraint for help.
    namespace detail {
        /// Range: accepts [lo, hi]. needs <= and <<. label: "lo..hi"
        template<typename T>
        class RangeFn {
            public:
                constexpr RangeFn(T lo, T hi) : _lo(lo), _hi(hi) {}

                std::string operator()(const T& v) const {
                    if (!(_lo <= v && v <= _hi))
                        return "value out of range.";
                    return "";
                }

                std::string label() const {
                    std::ostringstream oss;
                    oss << std::boolalpha << _lo << ".." << _hi;
                    return oss.str();
                }

            private:
                T _lo;
                T _hi;
        };

        /// Choices: accepts only listed values. needs == and <<. label: "a|b|c"
        template<typename T>
        class ChoicesFn {
            public:
                ChoicesFn(std::vector<T> vals) : _choices(std::move(vals)) {}

                std::string operator()(const T& v) const {
                    for (const auto& current : _choices)
                        if (v == current)
                            return "";
                    return "value not in allowed choices.";
                }

                std::string label() const {
                    std::ostringstream oss;
                    oss << std::boolalpha;
                    bool first = true;
                    for (const auto& current : _choices) {
                        if (!first) oss << '|';
                        oss << current;
                        first = false;
                    }
                    return oss.str();
                }

            private:
                std::vector<T> _choices;
        };

        /// Min: accepts >= min. needs <= and <<. hint: ">= min"
        template<typename T>
        class MinFn {
            public:
                constexpr MinFn(T min) : _min(min) {}

                std::string operator()(const T& v) const {
                    // positive form so NaN, for which every comparison is
                    // false, is rejected instead of accepted.
                    if (!(_min <= v))
                        return "value too small";
                    return "";
                }

                std::string hint() const {
                    std::ostringstream oss;
                    oss << std::boolalpha << ">= " << _min;
                    return oss.str();
                }

            private:
                T _min;
        };

        /// Max: accepts <= max. needs <= and <<. hint: "<= max"
        template<typename T>
        class MaxFn {
            public:
                constexpr MaxFn(T max) : _max(max) {}

                std::string operator()(const T& v) const {
                    if (!(v <= _max))
                        return "value too big";
                    return "";
                }

                std::string hint() const {
                    std::ostringstream oss;
                    oss << std::boolalpha << "<= " << _max;
                    return oss.str();
                }

            private:
                T _max;
        };

        /// FileExists: accepts only existing files. hint: "must exist"
        class FileExistsFn {
            public:
                std::string operator()(const std::filesystem::path& v) const {
                    std::error_code ec;
                    if (std::filesystem::is_directory(v, ec))
                        return v.string() + " is a directory";
                    if (!std::filesystem::is_regular_file(v, ec))
                        return "file does not exist";
                    return "";
                }

                std::string hint() const { return "must exist"; }
        };

        /// DirExists: accepts only existing directories. hint: "must be a directory"
        class DirExistsFn {
            public:
            std::string operator()(const std::filesystem::path& v) const {
                std::error_code ec;
                if (std::filesystem::is_regular_file(v, ec))
                    return v.string() + " is a regular file";
                if (!std::filesystem::is_directory(v, ec))
                    return "directory does not exist";
                return "";
            }

            std::string hint() const { return "must be a directory"; }
        };

        /// NonexistentPath: accepts only paths that do not exist. hint: "must not exist"
        class NonexistentPathFn {
            public:
                std::string operator()(const std::filesystem::path& v) const {
                    std::error_code ec;
                    // symlink_status, not exists: a dangling link reads as
                    // absent but still occupies the name, and creating there
                    // fails with EEXIST.
                    if (std::filesystem::exists(std::filesystem::symlink_status(v, ec)))
                        return "path already exists";
                    return "";
                }

                std::string hint() const { return "must not exist"; }
        };

        /// NonEmpty: accepts only non-empty values.    needs empty(). hint: "non-empty"
        class NonEmptyFn {
            public:
                template<typename T>
                requires requires (const T& v) { { v.empty() } -> std::convertible_to<bool>; }
                std::string operator()(const T& v) const {
                    if (v.empty())
                        return "value cannot be empty";
                    return "";
                }

                std::string hint() const { return "non-empty"; }
        };

    } // namespace detail

    /// Each comparing validator carries a const char* overload that maps to
    /// std::string. Without it T deduces as const char* and the validator keeps
    /// raw pointers: == would compare addresses instead of text, <= would order
    /// by address, and a pointer to anything but a literal dangles as soon as
    /// the caller's temporary dies. The overload makes the conversion implicit,
    /// so literals go straight into Choices(), Range(), Min() and Max().

    /// Usage:
    /// clap::Range(lo, hi)
    template<typename T>
    detail::RangeFn<T> Range(T lo, T hi) { return detail::RangeFn<T>(std::move(lo), std::move(hi)); }
    inline detail::RangeFn<std::string> Range(const char* lo, const char* hi) {
        return detail::RangeFn<std::string>(lo, hi);
    }

    /// Usage:
    /// clap::Choices(vals) where is a vector or initializer_list of T
    /// clap::Choices({a, b, c})
    template<typename T>
    detail::ChoicesFn<T> Choices(std::vector<T> vals) { return detail::ChoicesFn<T>(std::move(vals)); }
    template<typename T>
    detail::ChoicesFn<T> Choices(std::initializer_list<T> vals) { return detail::ChoicesFn<T>(vals); }
    inline detail::ChoicesFn<std::string> Choices(std::initializer_list<const char*> vals) {
        return detail::ChoicesFn<std::string>(std::vector<std::string>(vals.begin(), vals.end()));
    }

    /// Usage:
    /// clap::Min(min)
    template<typename T>
    detail::MinFn<T> Min(T min) { return detail::MinFn<T>(std::move(min)); }
    inline detail::MinFn<std::string> Min(const char* min) { return detail::MinFn<std::string>(min); }

    /// Usage:
    /// clap::Max(max)
    template<typename T>
    detail::MaxFn<T> Max(T max) { return detail::MaxFn<T>(std::move(max)); }
    inline detail::MaxFn<std::string> Max(const char* max) { return detail::MaxFn<std::string>(max); }

    /// Usage:
    /// clap::FileExists
    /// clap::DirExists
    /// clap::NonexistentPath
    /// clap::NonEmpty
    inline constexpr detail::FileExistsFn FileExists{};
    inline constexpr detail::DirExistsFn DirExists{};
    inline constexpr detail::NonexistentPathFn NonexistentPath{};
    inline constexpr detail::NonEmptyFn NonEmpty{};

} // namespace clap

// ===== TypedArgument.hpp =====
namespace clap {

    template<typename T, typename Derived>
    class TypedArgument : public Argument {
        public:
            TypedArgument(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            /// every typed argument consumes a value token. (Flag doesn't, and
            /// isn't typed.)
            bool takes_value() const noexcept override { return true; }

            /// the type is always shown; labelled validators narrow it after it.
            /// <string json|xml|yaml>, <int 1..10>
            std::string_view type_name() const override {
                if (!_label.empty()) return _label;
                return clap::TypeName<T>::value;
            }

            /// Restrict accepted values to an explicit set. needs == and <<
            Derived& choices(std::vector<T> allowed) {
                validator(clap::Choices(allowed));
                return self();
            }

            /// Restrict accepted values to [lo, hi] range. needs <= and <<
            Derived& range(T lo, T hi) {
                validator(clap::Range(lo, hi));
                return self();
            }

            const std::vector<std::string>& hints() const override { return _hints; }

            /// Register a custom validator. The function should return an empty
            /// string on success, or an error message on failure.
            ///
            /// Two optional members describe it in the help: label() narrows the
            /// type slot, for constraints on the shape of the token itself
            /// (<string json|xml|yaml>); hint() states a requirement next to the
            /// description ("must exist"), for everything else.
            template<typename F>
            Derived& validator(F func) {
                static_assert(std::is_invocable_r_v<std::string, const F&, const T&>,
                    "validator must be callable as std::string(const T&). "
                    "Check the value type: clap::FileExists/DirExists/NonexistentPath "
                    "need std::filesystem::path, clap::NonEmpty needs a type with .empty().");
                if constexpr ( requires { func.label(); }) {
                    std::string l = func.label();
                    if (!l.empty()) {
                        if (_label.empty())
                            _label = clap::TypeName<T>::value;
                        _label += " " + l;
                    }
                }
                if constexpr ( requires { func.hint(); }) {
                    std::string h = func.hint();
                    if (!h.empty())
                        _hints.push_back(std::move(h));
                }
                if constexpr (std::is_invocable_r_v<std::string, const F&, const T&>)
                    _validators.push_back(std::move(func));
                return self();
            }

            /// Keep this argument out of the help text and the usage line.
            /// It still parses exactly as before.
            Derived& hidden() {
                this->set_hidden();
                return self();
            }

        protected:
            /// parses a T value, then runs it past every registered validator
            T parse_value(std::string_view value) {
                T v = clap::parse_checked<T>(value, names(), type_name());
                validate(v, value);
                return v;
            }

        private:
            Derived& self() { return static_cast<Derived&>(*this); }

            /// runs the validators in registration order. The first one to
            /// return a reason throws, so only one is ever reported.
            void validate(const T& v, std::string_view raw) {
                for (const auto& f : _validators) {
                    std::string msg = f(v);
                    if (!msg.empty())
                        throw clap::InvalidValue(std::string(raw), std::string(names()),
                                                 std::string(type_name()), msg);
                }
            }

            std::vector<std::function<std::string(const T&)>> _validators;
            std::string _label;
            std::vector<std::string> _hints;
    };
}

// ===== Flag.hpp =====
namespace clap {
    /// A boolean switch like -v or --force. Convert to bool to read it.
    /// You can also call .count() to see how many times it was repeated.
    /// example: -vvv sets count() to 3 (if you want a level of verboseness).
    class Flag : public Argument {
        public:
            Flag(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            operator bool() const noexcept { return _value; }

            void parse(std::string_view, bool discard) noexcept override {
                if (!discard) {
                    _value = true;
                    _count++;
                }
            }

            std::string_view type_name() const override { return ""; }

            bool is_set() const noexcept override { return _value; }
            bool takes_value() const noexcept override { return false; }

            /// How many times the flag was set. 0 when absent, 3 for -vvv.
            /// Discarded occurrences (-/v) don't count.
            int count() const noexcept { return _count; }

            void reset() noexcept override {
                _value = false;
                _count = 0;
            }

            /// Keep this flag out of the help text and the usage line.
            /// It still parses exactly as before.
            Flag& hidden() {
                set_hidden();
                return *this;
            }

        private:
            bool _value = false;
            int _count = 0;
    };
}

// ===== Option.hpp =====
namespace clap {
    /// A named argument that takes one typed value, e.g. -c 10 or --count=10.
    /// CRTP: inherits from himself. this is used to return the derived type from
    /// methods like required() and default_value().
    template<typename T>
    class Option : public TypedArgument<T, Option<T>> {
        public:
            Option(std::string names, std::string description)
            : TypedArgument<T, Option<T>>(std::move(names), std::move(description)) {}

            void parse(std::string_view value, bool discard) override {
                auto v = this->parse_value(value);
                if (!discard) _value = std::move(v);
            }

            bool is_set() const noexcept override { return _value.has_value(); }

            /// Mark as required. Parsing fails if absent. Excludes default_value().
            Option<T>& required() {
                if (_default_value.has_value())
                    throw clap::ConfigError("cannot combine required() with default_value()");
                this->set_required();
                return *this;
            }

            std::string default_str() const override {
                if (!_default_value.has_value()) return "";
                std::ostringstream oss;
                oss << std::boolalpha << _default_value.value();
                return oss.str();
            }

            /// Set a fallback used when the option is absent. Excludes required().
            Option<T>& default_value(T val) {
                if (this->is_required())
                    throw clap::ConfigError("cannot combine default_value() with required()");
                _default_value = std::move(val);
                return *this;
            }

            /// Register an environment variable as a fallback source
            /// flag > env > default_value() > unset.
            Option<T>& from_env(const std::string& key) {
                _env_key = key;
                return *this;
            }

            std::string env_key() const override { return _env_key; }

            /// Fill from the env var when argv left this unset. Bad env values
            /// throw InvalidValue tagged with the source, caught by parse().
            void resolve_env() override {
                if (_value.has_value() || _env_key.empty())
                    return;
                const char *raw = std::getenv(_env_key.c_str());
                if (raw == nullptr)
                    return;
                try {
                    _value = this->parse_value(raw);
                } catch (const clap::InvalidValue&) {
                    throw clap::InvalidValue(raw, std::string(this->names()),
                                             std::string(this->type_name()),
                                             "from environment '" + _env_key + "'");
                }
            }

            /// The parsed value, else the default. Throws MissingValue if neither.
            const T& get() const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                throw clap::MissingValue(std::string(this->names()));
            }

            /// The parsed value, else the default, else a fallback. Never throws.
            T get_or(T fallback) const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                return fallback;
            }

            void reset() noexcept override { _value.reset(); }

        private:
            std::optional<T> _value;
            std::optional<T> _default_value;
            std::string _env_key;
    };
}

// ===== ValueList.hpp =====
namespace clap {
    /// Collects multiple parsed values of T into a list. Backs both a repeated
    /// named option (-t a -t b) and a variadic positional (prog a b c); the two
    /// differ only in how App routes tokens to them, not in how they store.
    /// CRTP: inherits from himself. this is used to return the derived type from
    /// methods like required() and default_value().
    template<typename T>
    class ValueList : public TypedArgument<T, ValueList<T>> {
    public:
        ValueList(std::string names, std::string description)
        : TypedArgument<T, ValueList<T>>(std::move(names), std::move(description)) {}

        void parse(std::string_view value, bool discard) override {
            auto v = this->parse_value(value);
            if (!discard) _values.push_back(std::move(v));
        }

        bool is_set() const noexcept override { return !_values.empty(); }
        bool is_multi() const noexcept override { return true; }

        /// Require at least one value. Parsing fails if none is given.
        /// Excludes default_value().
        ValueList<T>& required() {
            if (!_default_values.empty())
                throw clap::ConfigError("cannot combine required() with default_value()");
            this->set_required();
            return *this;
        }

        /// Set a fallback list used when no value is given. Excludes required().
        /// An empty list is the same as no default: get() returns empty either way.
        ValueList<T>& default_value(std::vector<T> values) {
            if (this->is_required())
                throw clap::ConfigError("cannot combine default_value() with required()");
            _default_values = std::move(values);
            return *this;
        }

        std::string default_str() const override {
            if (_default_values.empty()) return "";
            std::ostringstream oss;
            oss << std::boolalpha;
            for (size_t i = 0; i < _default_values.size(); ++i) {
                if (i) oss << ',';
                oss << _default_values[i];
            }
            return oss.str();
        }

        /// All collected values, else the default list. Empty when neither was
        /// given and not required; throws MissingValue only if this list is
        /// required but stayed empty.
        const std::vector<T>& get() const {
            if (_values.empty()) {
                if (this->is_required())
                    throw clap::MissingValue(std::string(this->names()));
                return _default_values;
            }
            return _values;
        }

        void reset() noexcept override { _values.clear(); }

    private:
        std::vector<T> _values;
        std::vector<T> _default_values;
    };
}

// ===== Positional.hpp =====
namespace clap {
    /// An order-based argument with no dash, e.g. an input file.
    /// Required unless given a default_value().
    /// CRTP: inherits from himself. this is used to return the derived type from
    /// methods like required() and default_value().
    template<typename T>
    class Positional : public TypedArgument<T, Positional<T>> {
        public:
            Positional(std::string names, std::string description)
            : TypedArgument<T, Positional<T>>(std::move(names), std::move(description)) {}

            void parse(std::string_view value, bool) override {
                _value = this->parse_value(value);
            }

            bool is_set() const noexcept override { return _value.has_value(); }

            bool is_required() const noexcept override { return !_default_value.has_value(); }

            /// Set a fallback value, making the positional optional.
            Positional<T>& default_value(T val) {
                _default_value = std::move(val);
                return *this;
            }

            std::string default_str() const override {
                if (!_default_value.has_value()) return "";
                std::ostringstream oss;
                oss << std::boolalpha << _default_value.value();
                return oss.str();
            }

            /// The parsed value, else the default. Throws MissingValue if neither.
            const T&  get() const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                throw clap::MissingValue(std::string(this->names()));
            }

            void reset() noexcept override { _value.reset(); }

        private:
            std::optional<T> _value;
            std::optional<T> _default_value;
    };
}

// ===== HelpFormatter.hpp =====
namespace clap {
    class Argument;

    /// Builds the usage line and full help text from an App's arguments.
    class HelpFormatter {
        public:
            using ArgList = std::vector<std::unique_ptr<Argument>>;

            HelpFormatter(std::string_view name, std::string_view description,
                          const ArgList& options, const ArgList& positionals,
                          std::vector<std::pair<std::string, std::string>> examples,
                          std::string_view footer = "", bool footer_wrap = true)
                : _name(name), _description(description), _examples(examples),
                  _footer(footer), _footer_wrap(footer_wrap) {
                      for (const auto& o : options)
                          if (!o->is_hidden())
                              _options.push_back(o.get());
                      for (const auto& p : positionals)
                          if (!p->is_hidden())
                              _positionals.push_back(p.get());
                  }

            /// The "Usage: ..." one-liner.
            std::string usage() const;
            /// Full help: usage, description, and aligned option tables.
            std::string help() const;

        private:
            /// Past this many lines the usage stops being a summary, and the
            /// optional options collapse into a single [OPTIONS]. A count of
            /// options would be the wrong measure: six one-letter flags fit on
            /// one line, three long ones do not.
            static constexpr size_t _usage_max_lines = 2;
            /// A name wider than this does not widen the name column; it runs
            /// over instead of pushing every other row right.
            static constexpr size_t _name_max = 24;
            /// Descriptions never start further right than this. A row whose
            /// name and type reach it puts its description on the next line.
            static constexpr size_t _desc_max = 34;
            /// A wrapped usage line continues under its first token, unless
            /// the program name is long enough to push that past this. Half
            /// the line: past that the tokens have less room than the indent.
            static constexpr size_t _usage_indent_max = 40;
            /// Total line width descriptions wrap at. Fixed, not detected: the
            /// terminal's real width costs an ioctl on POSIX and a different
            /// call on Windows, and 80 gets nearly all of the benefit (#41).
            static constexpr size_t _line_width = 80;

            std::string usage_token(const Argument& arg, bool positional) const;
            std::vector<std::string> usage_tokens(bool collapse) const;
            std::vector<std::string> pack(const std::vector<std::string>& tokens,
                                          const std::string& head, size_t indent) const;
            std::string name_col(const Argument& arg) const;
            std::string type_col(const Argument& arg) const;
            std::string annotation(const Argument& arg) const;
            std::string prefix_col(const Argument& arg, size_t name_w) const;
            std::string row(const Argument& arg, size_t name_w, size_t desc_col) const;
            std::vector<std::string> wrap(const std::string& text, size_t width) const;
            std::string table(const std::vector<const Argument*>& args, size_t name_w,
                              size_t desc_col) const;
            size_t name_width() const;
            size_t desc_column() const;

            std::string_view _name;
            std::string_view _description;
            std::vector<const Argument*> _options;
            std::vector<const Argument*> _positionals;
            std::vector<std::pair<std::string, std::string>> _examples;
            std::string_view _footer;
            bool _footer_wrap;
    };
}

// ===== App.hpp =====
namespace clap {
    class ArgCursor;

    /// The parser. Register arguments, then call parse(argc, argv).
    class App {
        public:
            /// name shows in the usage line; description shows in help.
            App(std::string name, std::string description);

            App(const App&) = delete;
            App& operator=(const App&) = delete;
            App(App&&) = delete;
            App& operator=(App&&) = delete;

            /// Register a value option, e.g. option<int>("-c,--count", "...").
            template<typename T>
            Option<T>& option(std::string names, std::string description,
                              std::source_location loc = std::source_location::current()) {
                static_assert(OptionValue<T>,
                    "clap: this option's value type is not usable. clap needs to "
                    "parse it from a string (give it operator>> or specialize "
                    "clap::ParseValue<T>) and print its default (give it "
                    "operator<<). Also specialize clap::TypeName<T> for its help "
                    "label -- see examples/custom_type.");
                auto option = std::make_unique<Option<T>>(std::move(names), std::move(description));
                option->set_location(loc);
                auto &ref = *option;
                add_argument(std::move(option));
                return ref;
            }

            /// Register a boolean flag, e.g. flag("-v,--verbose", "...").
            Flag& flag(std::string names, std::string description,
                       std::source_location loc = std::source_location::current()) {
                auto flag = std::make_unique<Flag>(std::move(names), std::move(description));
                flag->set_location(loc);
                auto &ref = *flag;
                add_argument(std::move(flag));
                return ref;
            }

            /// Register a repeatable option, e.g. multi_option<std::string>("-t,--tag", "...").
            template<typename T>
            ValueList<T>& multi_option(std::string names, std::string description,
                                       std::source_location loc = std::source_location::current()) {
                static_assert(OptionValue<T>,
                    "clap: this option's value type is not usable. clap needs to "
                    "parse it from a string (give it operator>> or specialize "
                    "clap::ParseValue<T>) and print its default (give it "
                    "operator<<). Also specialize clap::TypeName<T> for its help "
                    "label -- see examples/custom_type.");
                auto opt = std::make_unique<ValueList<T>>(std::move(names), std::move(description));
                opt->set_location(loc);
                auto& ref = *opt;
                add_argument(std::move(opt));
                return ref;
            }

            /// Register a variadic positional, e.g. variadic<std::string>("files", "...").
            /// Must be the last positional; greedily collects every remaining token.
            template<typename T>
            ValueList<T>& variadic(std::string name, std::string description,
                                   std::source_location loc = std::source_location::current()) {
                static_assert(OptionValue<T>,
                    "clap: this positional's value type is not usable. clap needs to "
                    "parse it from a string (give it operator>> or specialize "
                    "clap::ParseValue<T>) and print its default (give it "
                    "operator<<). Also specialize clap::TypeName<T> for its help "
                    "label -- see examples/custom_type.");
                auto pos = std::make_unique<ValueList<T>>(std::move(name), std::move(description));
                pos->set_location(loc);
                auto& ref = *pos;
                add_positional(std::move(pos));
                return ref;
            }

            /// Register a positional argument, e.g. positional<std::string>("input", "...").
            template<typename T>
            Positional<T>& positional(std::string name, std::string description,
                                      std::source_location loc = std::source_location::current()) {
                static_assert(OptionValue<T>,
                    "clap: this positional's value type is not usable. clap needs to "
                    "parse it from a string (give it operator>> or specialize "
                    "clap::ParseValue<T>) and print its default (give it "
                    "operator<<). Also specialize clap::TypeName<T> for its help "
                    "label -- see examples/custom_type.");
                auto pos = std::make_unique<Positional<T>>(std::move(name), std::move(description));
                pos->set_location(loc);
                auto &ref = *pos;
                add_positional(std::move(pos));
                return ref;
            }

            /// Parse the argument list. args[0] is the program name and is
            /// skipped, exactly as argv[0] is.
            /// Never throws on bad input; returns true on success,
            /// false if an error was recorded (see error()/error_kind()). It fills
            /// every value it can regardless. Registration still throws ConfigError.
            ///
            /// Two special forms are recognised:
            /// - "--" on its own: every token after it is treated as positional,
            ///   even ones that look like flags.
            /// - a "/" right after the dashes (e.g. -/v, --/count=3): parses and
            ///   validates the argument but discards its value, leaving it unset.
            bool parse(const std::vector<std::string>& args);

            /// Same, from what main() receives. Copies argv into a vector and
            /// calls the overload above.
            bool parse(int argc, char **argv);

            /// called by parse on entry. prevents weird/stale state when calling parse
            /// multiple times on the same app. We dont prevent re-entry to let the user
            /// keep control of his app state.
            void reset() noexcept;

            /// Full help message.
            std::string help() const;
            /// One-line usage summary string.
            std::string usage() const;

            /// Add an example usage line to the help message. The description is optional.
            void example(const std::string& example, const std::string& description = "", std::source_location loc = std::source_location::current()) {
                if (example.empty()) throw clap::ConfigError(loc, "example() cannot be called with an empty string");
                _examples.emplace_back(example, description);
            }

            /// Add a footer to the help message. The footer is printed after the examples.
            /// By default, the footer wraps like the rest of the help text. If you want to
            /// disable this behavior, call app.disable_footer_wrap() before calling this
            /// method.
            /// The footer is optional and can be empty (wont be displayed)
            void footer(const std::string& footer) {
                _footer = footer;
            }

            /// Disable text's wrapping in the footer. I made this so rendering ascii
            /// art in the footer works nicely, and regular footers dont need to be a
            /// properly formatted string.
            void disable_footer_wrap() { _footer_wrap = false; }

            /// The error text to print (message + usage line), empty when parse() succeeded.
            const std::string& error() const noexcept { return _error; }
            /// Which error parse() recorded. ErrorKind::OK before parse() runs and
            /// after a parse that succeeded.
            ErrorKind error_kind() const noexcept { return _error_kind; }

        private:
            std::string _name;
            std::string _description;
            std::vector<std::unique_ptr<Argument>> _arguments;
            std::vector<std::unique_ptr<Argument>> _positionals;

            /// A positional token and the argv slot it came from. Positionals
            /// are collected during the walk and assigned once it ends, so the
            /// slot has to be carried along for error ordering.
            using PositionalToken = std::pair<size_t, std::string>;
            std::vector<PositionalToken> _positional_tokens;

            /// A recorded parse error, tagged with its argv slot.
            struct Failure {
                size_t index;
                ErrorKind kind;
                std::string message;
            };

            /// index for a failure that belongs after the whole walk.
            static constexpr size_t after_argv = static_cast<size_t>(-1);
            std::string _error;
            ErrorKind _error_kind{ErrorKind::OK};
            bool _positional_mode = false;

            std::vector<std::pair<std::string, std::string>> _examples;
            std::string _footer;
            bool _footer_wrap = true;

            void add_argument(std::unique_ptr<Argument> arg);
            void add_positional(std::unique_ptr<Argument> pos);
            Argument* find_argument(std::string_view name);
            /// "did you mean '--x'?" for an unrecognised token, "" when nothing
            /// registered is close enough.
            std::string did_you_mean(std::string_view token) const;
            static bool starts_with(std::string_view str, std::string_view prefix);

            void dispatch(std::string_view token, ArgCursor& cursor, size_t index);
            void handle_positional(std::string_view token, size_t index);
            /// Hands the collected tokens to the positionals: required ones
            /// first in declaration order, then optionals take what is left
            /// over. Runs once, after the walk.
            void assign_positionals(std::vector<Failure>& failures);
            void feed(Argument& pos, const PositionalToken& token,
                      std::vector<Failure>& failures) const;
            void check_required() const;

            void parse_long_equals(std::string_view token, bool discard);
            void parse_short_cluster(std::string_view token, ArgCursor& cursor, bool discard);
            void parse_single(std::string_view token, ArgCursor& cursor, bool discard);
    };
}

#include <algorithm>
#include <cctype>
#include <cstddef>
#include <cstring>

// ===== damerau_osa.cpp =====
// Names shorter than this are not compared: at one or two characters every
// name is a near-miss for every other, so the suggestion would be noise.
namespace clap::detail {
inline constexpr size_t MIN_SUGGEST_LEN = 3;

inline std::string_view strip_dashes(std::string_view s) {
    size_t i = 0;
    while (i < s.size() && s[i] == '-') i++;
    return s.substr(i);
}
}

// levenshtein distance implementation. adds damerau transposition
// so mistakes like (--forec instead of --force) gives a smaller cost
inline int clap::detail::damerau_osa(const std::string& s1, const std::string& s2) {
    std::vector<std::vector<int>> d(s1.size() + 1, std::vector<int>(s2.size() + 1));
    size_t i, j;
    int cost = 0;

    // init d
    for (i = 0; i < s1.size() + 1; i++) d[i][0] = i;
    for (j = 0; j < s2.size() + 1; j++) d[0][j] = j;

    for (i = 1; i < s1.size() + 1; i++) {
        for (j = 1; j < s2.size() + 1; j++) {
            cost = (s1[i - 1] == s2[j - 1]) ? 0 : 1;
            d[i][j] = std::min({
                d[i - 1][j    ] + 1,
                d[i    ][j - 1] + 1,
                d[i - 1][j - 1] + cost
            });
            // transposition (osa)
            if (i > 1 && j > 1 && s1[i - 1] == s2[j - 2] && s1[i - 2] == s2[j - 1])
                d[i][j] = std::min(d[i][j], d[i - 2][j - 2] + cost);
        }
    }
    return d[s1.size()][s2.size()];
}

inline std::string clap::detail::suggest(std::string_view unknown,
                                  const std::vector<std::string>& candidates) {
    std::string input(clap::detail::strip_dashes(unknown));
    if (input.size() < clap::detail::MIN_SUGGEST_LEN)
        return "";

    const std::string* best = nullptr;
    int best_dist = 0;

    for (const std::string& candidate : candidates) {
        std::string name(clap::detail::strip_dashes(candidate));
        if (name.size() < clap::detail::MIN_SUGGEST_LEN)
            continue;
        int dist = clap::detail::damerau_osa(input, name);
        if (!best || dist < best_dist) {
            best_dist = dist;
            best = &candidate;
        }
    }

    if (!best)
        return "";

    // One edit tolerated per three characters of the longer name, so short
    // names stay strict and long ones do not demand a perfect guess.
    size_t len = std::max(input.size(), clap::detail::strip_dashes(*best).size());
    int max_dist = std::max(static_cast<int>(len) / 3, 1);

    return best_dist <= max_dist ? *best : "";
}

// ===== HelpFormatter.cpp =====
inline std::string clap::HelpFormatter::usage_token(const clap::Argument& arg, bool positional) const {
    if (positional) {
        std::string core = "<" + std::string(arg.names()) + ">";
        std::string tail = arg.is_multi() ? "..." : "";
        return arg.is_required() ? core + tail : "[" + core + "]" + tail;
    }
    if (!arg.takes_value())
        return "[" + std::string(arg.primary_name()) + "]";

    std::string core = std::string(arg.primary_name()) + " <" + std::string(arg.type_name()) + ">";
    std::string tail = arg.is_multi() ? "..." : "";
    return arg.is_required() ? core + tail : "[" + core + "]" + tail;
}

inline std::string clap::HelpFormatter::name_col(const clap::Argument& arg) const {
    std::string s = "  " + std::string(arg.names());
    if (arg.is_multi())
        s += "...";
    return s;
}

inline std::string clap::HelpFormatter::type_col(const clap::Argument& arg) const {
    if (arg.type_name().empty())
        return "";
    return "<" + std::string(arg.type_name()) + ">";
}

inline std::string clap::HelpFormatter::annotation(const clap::Argument& arg) const {
    std::string s;
    if (arg.is_required())
        s += " (required)";
    else if (!arg.default_str().empty())
        s += " (default: " + arg.default_str() + ")";
    if (!arg.env_key().empty())
        s += " (env: " + arg.env_key() + ")";
    for (const auto& hint : arg.hints())
        s += " (" + hint + ")";
    return s;
}

inline size_t clap::HelpFormatter::name_width() const {
    size_t max_w = 0;
    for (const auto* list : {&_options, &_positionals})
        for (const auto& a : *list) {
            const size_t w = name_col(*a).size() + 2;
            if (w <= _name_max)
                max_w = std::max(max_w, w);
        }
    return max_w == 0 ? _name_max : max_w;
}

inline size_t clap::HelpFormatter::desc_column() const {
    const size_t name_w = name_width();

    size_t max_w = 0;
    for (const auto* list : {&_options, &_positionals})
        for (const auto& a : *list) {
            const size_t w = prefix_col(*a, name_w).size() + 2;
            if (w <= _desc_max)
                max_w = std::max(max_w, w);
        }
    return max_w == 0 ? _desc_max : max_w;
}

inline std::string clap::HelpFormatter::prefix_col(const clap::Argument& arg,
                                                   size_t name_w) const {
    std::string prefix = name_col(arg);
    const std::string type = type_col(arg);
    if (type.empty())
        return prefix;
    if (prefix.size() < name_w)
        prefix.resize(name_w, ' ');
    else
        prefix += "  ";
    return prefix + type;
}

inline std::vector<std::string> clap::HelpFormatter::wrap(const std::string& text,
                                                          size_t width) const {
    std::vector<std::string> lines;
    std::istringstream paragraphs(text);
    std::string paragraph;

    while (std::getline(paragraphs, paragraph)) {
        std::istringstream words(paragraph);
        std::string word, line;

        while (words >> word) {
            if (line.empty())
                line = word;
            else if (line.size() + 1 + word.size() <= width)
                line += " " + word;
            else {
                lines.push_back(line);
                line = word;
            }
        }
        lines.push_back(line);
    }
    if (lines.empty())
        lines.push_back("");
    return lines;
}

inline std::string clap::HelpFormatter::row(const clap::Argument& arg, size_t name_w,
                                            size_t desc_col) const {
    std::string prefix = prefix_col(arg, name_w);

    static_assert(_desc_max < _line_width, "the description column must leave room");
    const std::vector<std::string> lines =
        wrap(std::string(arg.description()) + annotation(arg), _line_width - desc_col);

    std::ostringstream oss;
    if (prefix.size() + 2 <= desc_col) {
        prefix.resize(desc_col, ' ');
        oss << prefix << lines.front() << "\n";
    } else {
        oss << prefix << "\n" << std::string(desc_col, ' ') << lines.front() << "\n";
    }
    for (size_t i = 1; i < lines.size(); ++i)
        oss << std::string(desc_col, ' ') << lines[i] << "\n";
    return oss.str();
}

inline std::string clap::HelpFormatter::table(const std::vector<const Argument*>& args,
                                              size_t name_w, size_t desc_col) const {
    std::ostringstream oss;
    for (const auto& a : args)
        oss << row(*a, name_w, desc_col);
    return oss.str();
}

inline std::vector<std::string> clap::HelpFormatter::usage_tokens(bool collapse) const {
    std::vector<std::string> tokens;
    if (collapse)
        tokens.push_back("[OPTIONS]");
    for (const auto& a : _options)
        if (!collapse || a->is_required())
            tokens.push_back(usage_token(*a, false));
    for (const auto& p : _positionals)
        tokens.push_back(usage_token(*p, true));
    return tokens;
}

inline std::vector<std::string> clap::HelpFormatter::pack(
    const std::vector<std::string>& tokens, const std::string& head, size_t indent) const {
    std::vector<std::string> lines;
    std::string line = head;
    for (const auto& token : tokens) {
        if (line.size() + 1 + token.size() <= _line_width)
            line += " " + token;
        else {
            lines.push_back(line);
            line = std::string(indent, ' ') + token;
        }
    }
    lines.push_back(line);
    return lines;
}

inline std::string clap::HelpFormatter::usage() const {
    const std::string head = "Usage: " + std::string(_name);
    const size_t indent =
        head.size() + 1 <= _usage_indent_max ? head.size() + 1 : std::strlen("Usage: ");

    std::vector<std::string> lines = pack(usage_tokens(false), head, indent);
    if (lines.size() > _usage_max_lines)
        lines = pack(usage_tokens(true), head, indent);

    std::ostringstream oss;
    for (size_t i = 0; i < lines.size(); ++i)
        oss << (i ? "\n" : "") << lines[i];
    return oss.str();
}

inline std::string clap::HelpFormatter::help() const {
    std::ostringstream oss;
    oss << usage() << "\n\n";
    for (const auto& line : wrap(std::string(_description), _line_width))
        oss << line << "\n";

    const size_t name_w = name_width();
    const size_t desc_col = desc_column();

    if (!_positionals.empty())
        oss << "\nPOSITIONALS:\n" << table(_positionals, name_w, desc_col);

    if (!_options.empty())
        oss << "\nOPTIONS:\n" << table(_options, name_w, desc_col);

    if (!_examples.empty()) {
        oss << "\nEXAMPLES:\n";
        bool first = true;
        for (const auto& [example, description] : _examples) {
            if (!description.empty()) {
                if (!first)
                    oss << "\n";
                for (const auto& line : wrap(description, _line_width - 4))
                    oss << "  # " << line << "\n";
            }
            oss << "  > " << example << "\n";
            first = false;
        }
    }
    if (!_footer.empty()) {
        oss << "\n";
        if (_footer_wrap)
            for (const auto& line : wrap(std::string(_footer), _line_width))
                oss << line << "\n";
        else
            oss << _footer << "\n";
    }

    return oss.str();
}

// ===== App.cpp =====
namespace clap::detail {
    inline bool is_long_body(std::string_view body) {
        if (body.empty() || !std::isalnum(static_cast<unsigned char>(body[0])))
            return false;
        for (char c : body)
            if (!std::isalnum(static_cast<unsigned char>(c)) && c != '-' && c != '_')
                return false;
        return true;
    }

    // accepts exactly two formats:
    // -f (single dash, single char)
    // --flag (double dash, long)
    // Anything else -- --f, spaces, --- is out.
    inline bool valid_option_name(std::string_view name) {
        if (name.size() < 2 || name[0] != '-')
            return false;
        if (name[1] == '-') {              // double dash: needs a long body
            auto body = name.substr(2);
            return body.size() >= 2 && is_long_body(body);
        }
        auto body = name.substr(1);        // single dash
        // short: any char but space, dash, and the two the grammar reserves --
        // '/' is the discard sigil, '=' the long-option separator, so '-/' and
        // '-=' would register but could never be routed to.
        if (body.size() == 1)
            return body[0] != '-' && body[0] != '/' && body[0] != '=' &&
                   !std::isspace(static_cast<unsigned char>(body[0]));
        return false;
    }
}

inline clap::App::App(std::string name, std::string description)
    : _name(std::move(name)), _description(std::move(description)) {
}

inline void clap::App::add_argument(std::unique_ptr<Argument> arg) {
    if (arg->raw_names().empty())
        throw clap::ConfigError(arg->location(),
            "argument registered with no valid name");
    const auto& names = arg->raw_names();
    for (size_t i = 0; i < names.size(); ++i) {
        const auto& n = names[i];
        if (!clap::detail::valid_option_name(n))
            throw clap::ConfigError(arg->location(),
                "invalid option name '" + n + "' (expected -f or --flag)");
        if (std::find(names.begin(), names.begin() + i, n) != names.begin() + i)
            throw clap::ConfigError(arg->location(),
                "redeclaration of flag " + n);
        for (const auto& existing : _arguments)
            if (existing->matches(n))
                throw clap::ConfigError(arg->location(),
                    "redeclaration of flag " + n, existing->location());
    }
    _arguments.push_back(std::move(arg));
}

inline void clap::App::add_positional(std::unique_ptr<Argument> pos) {
    const auto& names = pos->raw_names();
    if (names.size() != 1)
        throw clap::ConfigError(pos->location(),
            "positional registered with an empty name or a comma (a positional has exactly one name)"
    );
    const auto& name = names.front();
    if (!clap::detail::is_long_body(name))
        throw clap::ConfigError(pos->location(),
            "invalid positional name '" + name + "' (letters, digits, '-' and '_', "
            "starting with a letter or a digit)");
    if (!_positionals.empty() && _positionals.back()->is_multi())
        throw clap::ConfigError(pos->location(),
            "positional '" + name + "' declared after variadic positional '"
            + _positionals.back()->raw_names().front() + "' (a variadic must be last)",
            _positionals.back()->location());
    for (const auto& existing : _positionals) {
        if (existing->matches(name))
            throw clap::ConfigError(pos->location(),
                "redeclaration of positional " + name, existing->location());
    }
    _positionals.push_back(std::move(pos));
}

inline clap::Argument* clap::App::find_argument(std::string_view token) {
    for (auto& arg : _arguments)
        if (arg->matches(token)) return arg.get();
    return nullptr;
}

inline std::string clap::App::did_you_mean(std::string_view token) const {
    std::vector<std::string> candidates;
    for (const auto& arg : _arguments)
        for (const auto& name : arg->raw_names())
            candidates.push_back(name);

    std::string match = clap::detail::suggest(token, candidates);
    return match.empty() ? "" : "did you mean '" + match + "'?";
}

inline bool clap::App::starts_with(std::string_view str, std::string_view prefix) {
    return str.size() >= prefix.size() &&
        str.compare(0, prefix.size(), prefix) == 0;
}

inline std::string clap::App::help() const {
    return HelpFormatter(
        _name,
        _description,
        _arguments,
        _positionals,
        _examples,
        _footer,
        _footer_wrap
    ).help();
}

inline std::string clap::App::usage() const {
    return HelpFormatter(
        _name,
        _description,
        _arguments,
        _positionals,
        _examples,
        _footer,
        _footer_wrap
    ).usage();
}

inline void clap::App::dispatch(std::string_view token, ArgCursor& cursor, size_t index) {
    // a bare "-" is the POSIX name for stdin: a value, not a flag.
    if (_positional_mode || !starts_with(token, "-") || token == "-") {
        handle_positional(token, index);
        return;
    }
    std::string_view original = token;
    size_t dashes = starts_with(token, "--") ? 2 : 1;
    bool discard = token.size() > dashes && token[dashes] == '/';
    std::string clean;
    if (discard) {
        clean = std::string(token.substr(0, dashes)) + std::string(token.substr(dashes + 1));
        token = clean;
    }
    // "--=value", "--/", "-/": nothing but dashes left of the '='. Report the
    // token the user typed, not the truncated name.
    if (token.substr(0, token.find('=')).size() <= dashes)
        throw clap::UnknownArgument(std::string(original));

    if (starts_with(token, "--") && token.find("=") != std::string_view::npos)
        parse_long_equals(token, discard);
    else if (!starts_with(token, "--") && token.size() > 2)
        parse_short_cluster(token, cursor, discard);
    else
        parse_single(token, cursor, discard);
}

inline bool clap::App::parse(int argc, char **argv) {
    return parse(std::vector<std::string>(argv, argv + argc));
}

inline bool clap::App::parse(const std::vector<std::string>& args) {
    reset();
    ArgCursor cursor(args);
    std::vector<Failure> failures;

    while (cursor.has_next()) {
        size_t index = cursor.position();
        try {
            std::string_view token = cursor.next();
            if (token == "--" && !_positional_mode) {
                _positional_mode = true;
                continue;
            }
            dispatch(token, cursor, index);
        } catch (const clap::ParseException& e) {
            failures.push_back({index, e.kind(), e.what()});
        }
    }

    // Runs even after a failure, so the values that did parse still fill in.
    assign_positionals(failures);

    if (failures.empty()) {
        for (auto& arg : _arguments) {
            try {
                arg->resolve_env();
            } catch (const clap::ParseException& e) {
                failures.push_back({after_argv, e.kind(), e.what()});
            }
        }
    }

    if (failures.empty()) {
        try {
            check_required();
        } catch (const clap::ParseException& e) {
            failures.push_back({after_argv, e.kind(), e.what()});
        }
    }


    if (!failures.empty()) {
        const Failure& first = *std::min_element(failures.begin(), failures.end(),
            [](const Failure& a, const Failure& b) { return a.index < b.index; });
        _error = "Error: " + first.message + "\n" + usage() + "\n";
        _error_kind = first.kind;
        return false;
    }
    _error.clear();
    _error_kind = clap::ErrorKind::OK;
    return true;
}

inline void clap::App::reset() noexcept {
    _positional_tokens.clear();
    _positional_mode = false;
    _error.clear();
    _error_kind = clap::ErrorKind::OK;
    for (auto& a : _arguments)   a->reset();
    for (auto& p : _positionals) p->reset();
}

inline void clap::App::handle_positional(std::string_view token, size_t index) {
    _positional_tokens.emplace_back(index, std::string(token));
}

inline void clap::App::feed(Argument& pos, const PositionalToken& token,
                            std::vector<Failure>& failures) const {
    try {
        pos.parse(token.second);
    } catch (const clap::ParseException& e) {
        failures.push_back({token.first, e.kind(), e.what()});
    }
}

inline void clap::App::assign_positionals(std::vector<Failure>& failures) {
    // A required variadic needs one token like any other required positional;
    // the rest of what it eats comes out of the surplus.
    size_t required = 0;
    for (const auto& pos : _positionals)
        if (pos->is_required())
            ++required;

    const size_t total = _positional_tokens.size();
    size_t surplus = total > required ? total - required : 0;
    size_t next = 0;

    for (auto& pos : _positionals) {
        if (pos->is_multi()) {         // variadic: always last, so it takes everything left
            while (next < total)
                feed(*pos, _positional_tokens[next++], failures);
            break;
        }
        if (next >= total)
            break;
        if (!pos->is_required()) {     // an optional only eats out of the surplus
            if (surplus == 0)
                continue;
            --surplus;
        }
        feed(*pos, _positional_tokens[next++], failures);
    }

    if (next < total) {
        const auto& [index, token] = _positional_tokens[next];
        failures.push_back({index, clap::ErrorKind::UnknownArgument,
                            "Unknown argument: " + token});
    }
}

// --option=value
inline void clap::App::parse_long_equals(std::string_view token, bool discard) {
    auto eq = token.find('=');
    auto arg_name  = token.substr(0, eq);
    auto arg_value = token.substr(eq + 1);
    auto *arg = find_argument(arg_name);
    if (!arg)
        throw clap::UnknownArgument(std::string(arg_name), did_you_mean(arg_name));
    if (!arg->takes_value())
        throw clap::UnexpectedValue(std::string(arg_name));
    arg->parse(arg_value, discard);
}

// short cluster: -vf, -c10, -c-5, -vc 10
inline void clap::App::parse_short_cluster(std::string_view token, ArgCursor& cursor, bool discard) {
    for (size_t j = 1; j < token.size(); ++j) {
        std::string short_name{'-', token[j]};
        auto *arg = find_argument(short_name);
        if (!arg)
            throw clap::UnknownArgument(short_name, did_you_mean(short_name));
        if (arg->takes_value()) {
            auto attached = token.substr(j + 1);
            if (!attached.empty()) {
                // '=' is a long-option separator; a short option attaches directly.
                if (attached.front() == '=')
                    throw clap::InvalidValue(std::string(attached), short_name,
                        std::string(arg->type_name()),
                        "short options take the value attached: '" + short_name
                        + std::string(attached.substr(1)) + "'");
                arg->parse(attached, discard);
            }
            else if (cursor.next_is_value())
                arg->parse(cursor.next(), discard);
            else
                throw clap::MissingValue(short_name);
            return;
        }
        arg->parse("", discard);
    }
}

inline void clap::App::parse_single(std::string_view token, ArgCursor& cursor, bool discard) {
    auto *arg = find_argument(token);
    if (!arg)
        throw clap::UnknownArgument(std::string(token), did_you_mean(token));

    if (arg->takes_value()) {
        if (!cursor.next_is_value())
            throw clap::MissingValue(std::string(token));
        arg->parse(cursor.next(), discard);
    } else {
        arg->parse("", discard);
    }
}

inline void clap::App::check_required() const {
    for (const auto& arg : _arguments)
        if (arg->is_required() && !arg->is_set())
            throw clap::MissingRequiredArgument(std::string(arg->names()));
    for (const auto& pos : _positionals)
        if (pos->is_required() && !pos->is_set())
            throw clap::MissingRequiredArgument(std::string(pos->names()));
}
