// ==========================================================================
// clap — single-header build. GENERATED by tools/build_single_header.py
// DO NOT EDIT. Edit src/ and rerun the script.
// ==========================================================================

/**
 * @file clap.hpp
 * @brief CLAP - C++ Command Line Argument Parser
 *
 * @details
 * CLAP is a lightweight, header-only C++ library for parsing command line arguments.
 *
 * @section Features
 * - Flags (e.g. -v, --verbose)
 * - Options with values (e.g. -o value, --output=value)
 * - Positional arguments (e.g. input files)
 * - Multi-value options (e.g. --include=dir1 --include=dir2)
 * - Required and optional arguments
 * - Default value support
 * - Automatic usage and help message generation
 *
 * @section Usage
 * Include this header and use the clap namespace to parse command line arguments.
 *
 * @author Lucas Pujol
 * @version dev
 */

#pragma once

#define CLAP_VERSION "dev"

#include <exception>
#include <istream>
#include <memory>
#include <optional>
#include <ostream>
#include <source_location>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

// ===== ClapExceptions.hpp =====
namespace clap {
    /// What kind of error App::parse() recorded. Query via App::error_kind().
    enum class ErrorKind {
        /// A token was passed that matches no registered argument.
        UnknownArgument,
        /// A value-taking argument was given no value.
        MissingValue,
        /// A flag was given a value, e.g. --verbose=1.
        UnexpectedValue,
        /// A value had the wrong format for its type.
        InvalidValue,
        /// A required argument was absent.
        MissingRequiredValue,
    };

    /// Base of every clap error. Catch this to handle them all.
    class ClapException : public std::exception {
        public:
            ClapException(const std::string& message) : _message(message) {}

            const char* what() const noexcept override {
                return _message.c_str();
            }

        private:
            std::string _message;
    };

    /// Base of the errors App::parse() reports. parse() catches these internally
    /// and records them as error state, so they never escape it. They still
    /// surface from Option::get() and friends, where they mean the caller read a
    /// value that was never set.
    class ParseException : public ClapException {
        public:
            ParseException(ErrorKind kind, const std::string& message)
                : ClapException(message), _kind(kind) {}

            /// Which ErrorKind this maps to in App::error_kind().
            ErrorKind kind() const noexcept { return _kind; }

        private:
            ErrorKind _kind;
    };

    /// An argument was passed that was never registered.
    class UnknownArgument : public ParseException {
        public:
            UnknownArgument(const std::string& arg)
                : ParseException(ErrorKind::UnknownArgument,
                                 "Unknown argument: " + arg) {}
    };

    /// A value-taking argument was given no value.
    class MissingValue : public ParseException {
        public:
            MissingValue(const std::string& arg)
                : ParseException(ErrorKind::MissingValue,
                                 "Missing value for argument: " + arg) {}
    };

    /// A flag was given a value, e.g. --verbose=1.
    class UnexpectedValue : public ParseException {
        public:
            UnexpectedValue(const std::string& arg)
                : ParseException(ErrorKind::UnexpectedValue,
                                 "flag '" + arg + "' does not take a value") {}
    };

    /// A required argument was missing.
    class MissingRequiredArgument : public ParseException {
        public:
            MissingRequiredArgument(const std::string& arg)
                : ParseException(ErrorKind::MissingRequiredValue,
                                 "Missing required argument: " + arg) {}
    };

    /// A value had the wrong format for its type.
    class InvalidValue : public ParseException {
        public:
            InvalidValue(const std::string& value, const std::string& arg,
                         const std::string& type)
                : ParseException(ErrorKind::InvalidValue,
                                 "invalid value '" + value + "' for '" + arg + "'"
                                 + (type.empty() ? "" : " (expected " + type + ")")) {}
    };

    /// The parser was set up wrong. Thrown while registering, not while parsing,
    /// so parse() never catches it: it means the program itself is buggy.
    class ConfigError : public ClapException {
        public:
            ConfigError(const std::string& msg)
                : ClapException("Configuration error: " + msg) {}

            /// Located, clang-style:
            /// "file:line:col: error: <msg>".
            /// loc points at the caller that registered the offending argument.
            ConfigError(const std::source_location& loc, const std::string& msg)
                : ClapException("\n" + prefix(loc) + "error: " + msg) {}

            /// Redeclaration: as above, plus a "previous definition" line at prev.
            ConfigError(const std::source_location& loc, const std::string& msg,
                        const std::source_location& prev)
                : ClapException("\n" + prefix(loc) + "error: " + msg + "\n" +
                                prefix(prev) + "previous definition") {}

        private:
            static std::string prefix(const std::source_location& loc) {
                return std::string(loc.file_name()) + ":" +
                       std::to_string(loc.line()) + ":" +
                       std::to_string(loc.column()) + ": ";
            }
    };

    /// A raw value failed to parse. Internal signal from a ParseValue
    /// specialization; parse_checked() turns it into an InvalidValue.
    class ParseError : public ClapException {
        public:
            ParseError(const std::string& msg)
                : ClapException("Parse error: " + msg) {}
    };
}

// ===== TypeNames.hpp =====
namespace clap {
    /// Label shown for a value type in help output, e.g. "<int>".
    /// Specialize for a custom type to give it a name.
    template<typename T> struct TypeName    { static constexpr std::string_view value = "unknown"; };

    template<> struct TypeName<int>         { static constexpr std::string_view value = "int"; };
    template<> struct TypeName<float>       { static constexpr std::string_view value = "float"; };
    template<> struct TypeName<double>      { static constexpr std::string_view value = "double"; };
    template<> struct TypeName<bool>        { static constexpr std::string_view value = "bool"; };
    template<> struct TypeName<std::string> { static constexpr std::string_view value = "string"; };
}

// ===== Argument.hpp =====
namespace clap {
    /// Base of every argument type. Holds names and description;
    /// subclasses decide how to parse and store a value.
    class Argument {
        public:
            Argument(std::string names, std::string description)
                : _names_raw(std::move(names)),
                  _names(split(_names_raw, ',')),
                  _description(std::move(description)) {}
            virtual ~Argument() = default;

            /// Consume a raw token as this argument's value.
            virtual void parse(std::string_view value, bool discard = false) = 0;
            /// Type label for help, e.g. "int". Empty for flags.
            virtual std::string_view type_name() const = 0;

            /// True once a value has been parsed.
            virtual bool is_set() const noexcept = 0;
            /// True if this argument consumes a value token.
            virtual bool takes_value() const noexcept = 0;
            /// True if it can be repeated to collect a list.
            virtual bool is_multi() const noexcept { return false; }

            /// Rendered default value for help, or empty if none.
            virtual std::string default_str() const { return ""; }

            std::string_view names() const noexcept { return _names_raw; }
            std::string_view description() const noexcept { return _description; }
            virtual bool is_required() const noexcept { return _required; }

            const std::vector<std::string>& raw_names() const noexcept { return _names; }

            /// Shortest registered name, preferred for the usage summary (e.g. "-v").
            std::string_view primary_name() const noexcept {
                std::string_view best;
                for (const auto& n : _names)
                    if (best.empty() || n.size() < best.size())
                        best = n;
                return best;
            }

            /// Where this argument was registered, for diagnostics. Set by App
            /// right after construction, so it points at the caller's site.
            void set_location(const std::source_location& loc) noexcept { _loc = loc; }
            const std::source_location& location() const noexcept { return _loc; }

            /// True if token matches one of this argument's names.
            bool matches(std::string_view name) const {
                for (const auto& arg_name : _names) {
                    if (arg_name == name)
                        return true;
                }
                return false;
            }

        protected:
            void set_required() noexcept { _required = true; }

        private:
            std::string _names_raw;
            std::vector<std::string> _names;
            std::string _description;
            bool _required = false;
            std::source_location _loc{};

            static std::vector<std::string> split(const std::string &str, char delimiter) {
                std::vector<std::string> tokens;
                std::istringstream iss(str);
                std::string token;

                while (std::getline(iss, token, delimiter)) {
                    token.erase(0, token.find_first_not_of(" \t\n\r\f\v"));
                    token.erase(token.find_last_not_of(" \t\n\r\f\v") + 1);
                    if (!token.empty())
                        tokens.push_back(token);
                }
                return tokens;
            }
    };
}

// ===== ArgCursor.hpp =====
namespace clap {
    /// Walks argv left to right, one token at a time (skips argv[0]).
    class ArgCursor {
        public:
            ArgCursor(int argc, char** argv) noexcept
                : _argc(argc), _argv(argv), _pos(1) {}

            bool has_next() const noexcept { return _pos < _argc; }

            /// Next token without moving. Precondition: has_next().
            std::string_view peek() const noexcept { return _argv[_pos]; }

            /// Next token, then advance. Precondition: has_next().
            std::string_view next() noexcept { return _argv[_pos++]; }

            /// True if a next token exists and does not look like a flag.
            bool next_is_value() const noexcept {
                return has_next() && (peek().empty() || peek().front() != '-');
            }

        private:
            int _argc;
            char** _argv;
            int _pos;
    };
}

// ===== ParseValue.hpp =====
namespace clap {
    /// Converts a string into T with operator>>. Specialize for custom parsing.
    template<typename T>
    concept StreamExtractable = requires(std::istream& is, T& v) { is >> v; };

    template<typename T>
    concept StreamInsertable = requires(std::ostream& os, const T& v) { os << v; };

    template<typename T>
    struct ParseValue;

    /// Default parser for any type readable with operator>>.
    template<StreamExtractable T>
    struct ParseValue<T> {
        static T parse(std::string_view str) {
            std::istringstream iss{std::string(str)};
            T val;
            if (!(iss >> val) || !iss.eof())
                throw clap::ParseError("Failed to parse value");
            return val;
        }
    };

    template<>
    struct ParseValue<std::string> {
        static std::string parse(std::string_view str) {
            return std::string(str);
        }
    };

    /// either ParseValue<T> is specialized, or T is stream-extractable. 
    template<typename T>
    concept Parseable = requires(std::string_view s) { ParseValue<T>::parse(s); };

    /// The full contract for a clap value type: parseable from a string, and
    /// printable via operator<< so its default value can appear in help output.
    template<typename T>
    concept OptionValue = Parseable<T> && StreamInsertable<T>;

    /// Parses value into T, turning any failure into an InvalidValue error.
    template<typename T>
    T parse_checked(std::string_view value, std::string_view name, std::string_view type) {
        try {
            return ParseValue<T>::parse(value);
        } catch (const clap::ParseError&) {
            throw clap::InvalidValue(std::string(value), std::string(name), std::string(type));
        }
    }
}

// ===== Flag.hpp =====
namespace clap {
    /// A boolean switch like -v or --force. Convert to bool to read it.
    class Flag : public Argument {
        public:
            Flag(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            operator bool() const noexcept { return _value; }

            void parse(std::string_view, bool discard) override {
                if (!discard) _value = true;
            }
            std::string_view type_name() const override { return ""; }

            bool is_set() const noexcept override { return _value; }
            bool takes_value() const noexcept override { return false; }

        private:
            bool _value = false;
    };
}

// ===== Option.hpp =====
namespace clap {
    /// A named argument that takes one typed value, e.g. -c 10 or --count=10.
    template<typename T>
    class Option : public Argument {
        public:
            Option(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            void parse(std::string_view value, bool discard) override {
                auto v = clap::parse_checked<T>(value, names(), type_name());
                if (!discard) _value = std::move(v);
            }

            std::string_view type_name() const override {
                return clap::TypeName<T>::value;
            }
            bool is_set() const noexcept override { return _value.has_value(); }

            /// Mark as required. Parsing fails if absent. Excludes default_value().
            Option<T>& required() {
                if (_default_value.has_value())
                    throw clap::ConfigError("cannot combine required() with default_value()");
                set_required();
                return *this;
            }

            /// option always takes a value, so this is true. (Flag overrides to false.)
            bool takes_value() const noexcept override { return true; }

            std::string default_str() const override {
                if (!_default_value.has_value()) return "";
                std::ostringstream oss;
                oss << _default_value.value();
                return oss.str();
            }

            /// Set a fallback used when the option is absent. Excludes required().
            Option<T>& default_value(T val) {
                if (is_required())
                    throw clap::ConfigError("cannot combine default_value() with required()");
                _default_value = std::move(val);
                return *this;
            }

            /// The parsed value, else the default. Throws MissingValue if neither.
            const T& get() const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                throw clap::MissingValue(std::string(names()));
            }

            /// The parsed value, else the default, else a fallback. Never throws.
            T get_or(T fallback) const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                return fallback;
            }

        private:
            std::optional<T> _value;
            std::optional<T> _default_value;
    };
}

// ===== MultiOption.hpp =====
namespace clap {
    /// A named option repeated to collect a list, e.g. -t a -t b.
    template<typename T>
    class MultiOption : public Argument {
    public:
        MultiOption(std::string names, std::string description)
        : Argument(std::move(names), std::move(description)) {}

        void parse(std::string_view value, bool discard) override {
            auto v = clap::parse_checked<T>(value, names(), type_name());
            if (!discard) _values.push_back(std::move(v));

        }

        std::string_view type_name() const override {
            return clap::TypeName<T>::value;
        }

        bool is_set() const noexcept override { return !_values.empty(); }
        bool takes_value() const noexcept override { return true; }
        bool is_multi() const noexcept override { return true; }

        /// Mark as required. Parsing fails if the flag never appears.
        MultiOption<T>& required() {
            set_required();
            return *this;
        }

        /// All collected values. Throws MissingValue if none were given.
        const std::vector<T>& get() const {
            if (_values.empty())
                throw clap::MissingValue(std::string(names()));
            return _values;
        }

    private:
        std::vector<T> _values;
    };
}

// ===== Positional.hpp =====
namespace clap {
    /// An order-based argument with no dash, e.g. an input file.
    /// Required unless given a default_value().
    template<typename T>
    class Positional : public Argument {
        public:
            Positional(std::string names, std::string description)
            : Argument(std::move(names), std::move(description)) {}

            void parse(std::string_view value, bool) override {
                _value = clap::parse_checked<T>(value, names(), type_name());
            }

            std::string_view type_name() const override {
                return clap::TypeName<T>::value;
            }

            bool is_set() const noexcept override { return _value.has_value(); }
            bool takes_value() const noexcept override { return true; }

            bool is_required() const noexcept override { return !_default_value.has_value(); }

            /// Set a fallback value, making the positional optional. 
            Positional<T>& default_value(T val) {
                _default_value = std::move(val);
                return *this;
            }

            std::string default_str() const override {
                if (!_default_value.has_value()) return "";
                std::ostringstream oss;
                oss << _default_value.value();
                return oss.str();
            }

            /// The parsed value, else the default. Throws MissingValue if neither.
            const T &get() const {
                if (_value.has_value())
                    return _value.value();
                if (_default_value.has_value())
                    return _default_value.value();
                throw clap::MissingValue(std::string(names()));
            }

        private:
            std::optional<T> _value;
            std::optional<T> _default_value;
    };
}

// ===== HelpFormatter.hpp =====
namespace clap {
    class Argument;

    /// Builds the usage line and full help text from an App's arguments.
    class HelpFormatter {
        public:
            using ArgList = std::vector<std::unique_ptr<Argument>>;

            HelpFormatter(std::string_view name, std::string_view description,
                          const ArgList& options, const ArgList& positionals)
                : _name(name), _description(description),
                  _options(options), _positionals(positionals) {}

            /// The "Usage: ..." one-liner.
            std::string usage() const;
            /// Full help: usage, description, and aligned option tables.
            std::string help() const;

        private:
            std::string usage_token(const Argument& arg, bool positional) const;
            std::string name_col(const Argument& arg) const;
            std::string type_col(const Argument& arg) const;
            std::string annotation(const Argument& arg) const;
            size_t name_width() const;
            size_t type_width() const;

            std::string_view _name;
            std::string_view _description;
            const ArgList& _options;
            const ArgList& _positionals;
    };
}

// ===== App.hpp =====
namespace clap {
    class ArgCursor;

    /// The parser. Register arguments, then call parse(argc, argv).
    class App {
        public:
            /// name shows in the usage line; description shows in help.
            App(std::string name, std::string description);

            App(const App&) = delete;
            App& operator=(const App&) = delete;
            App(App&&) = delete;
            App& operator=(App&&) = delete;

            /// Register a value option, e.g. option<int>("-c,--count", "...").
            template<typename T>
            Option<T>& option(std::string names, std::string description,
                              std::source_location loc = std::source_location::current()) {
                static_assert(OptionValue<T>,
                    "clap: this option's value type is not usable. clap needs to "
                    "parse it from a string (give it operator>> or specialize "
                    "clap::ParseValue<T>) and print its default (give it "
                    "operator<<). Also specialize clap::TypeName<T> for its help "
                    "label -- see examples/custom_type.");
                auto option = std::make_unique<Option<T>>(std::move(names), std::move(description));
                option->set_location(loc);
                auto &ref = *option;
                add_argument(std::move(option));
                return ref;
            }

            /// Register a boolean flag, e.g. flag("-v,--verbose", "...").
            Flag& flag(std::string names, std::string description,
                       std::source_location loc = std::source_location::current()) {
                auto flag = std::make_unique<Flag>(std::move(names), std::move(description));
                flag->set_location(loc);
                auto &ref = *flag;
                add_argument(std::move(flag));
                return ref;
            }

            /// Register a repeatable option, e.g. multi_option<std::string>("-t,--tag", "...").
            template<typename T>
            MultiOption<T>& multi_option(std::string names, std::string description,
                                         std::source_location loc = std::source_location::current()) {
                static_assert(Parseable<T>,
                    "clap: this option's value type cannot be parsed from a string. "
                    "Give it operator>> or specialize clap::ParseValue<T> (and "
                    "clap::TypeName<T> for its help label) -- see examples/custom_type.");
                auto opt = std::make_unique<MultiOption<T>>(std::move(names), std::move(description));
                opt->set_location(loc);
                auto& ref = *opt;
                add_argument(std::move(opt));
                return ref;
            }

            /// Register a positional argument, e.g. positional<std::string>("input", "...").
            template<typename T>
            Positional<T>& positional(std::string name, std::string description,
                                      std::source_location loc = std::source_location::current()) {
                static_assert(OptionValue<T>,
                    "clap: this positional's value type is not usable. clap needs to "
                    "parse it from a string (give it operator>> or specialize "
                    "clap::ParseValue<T>) and print its default (give it "
                    "operator<<). Also specialize clap::TypeName<T> for its help "
                    "label -- see examples/custom_type.");
                auto pos = std::make_unique<Positional<T>>(std::move(name), std::move(description));
                pos->set_location(loc);
                auto &ref = *pos;
                _positionals.push_back(std::move(pos));
                return ref;
            }

            /// Parse argv. Never throws on bad input; returns true on success,
            /// false if an error was recorded (see error()/error_kind()). It fills
            /// every value it can regardless. Registration still throws ConfigError.
            bool parse(int argc, char **argv);
            /// Full help message.
            std::string help() const;
            /// One-line usage summary string.
            std::string usage() const;

            /// The error text to print (message + usage line), empty when parse() succeeded.
            const std::string& error() const noexcept { return _error; }
            /// Which error parse() recorded. Precondition: parse() returned false.
            ErrorKind error_kind() const noexcept { return _error_kind; }

        private:
            std::string _name;
            std::string _description;
            std::vector<std::unique_ptr<Argument>> _arguments;
            std::vector<std::unique_ptr<Argument>> _positionals;
            size_t _positional_idx = 0;
            std::string _error;
            ErrorKind _error_kind{};
            bool _positional_mode = false;

            void add_argument(std::unique_ptr<Argument> arg);
            Argument* find_argument(std::string_view name);
            static bool starts_with(std::string_view str, std::string_view prefix);

            void dispatch(std::string_view token, ArgCursor& cursor);
            void handle_positional(std::string_view token);
            void check_required() const;

            void parse_long_equals(std::string_view token, bool discard);
            void parse_short_cluster(std::string_view token, ArgCursor& cursor, bool discard);
            void parse_single(std::string_view token, ArgCursor& cursor, bool discard);
    };
}

#ifdef CLAP_IMPLEMENTATION

#include <algorithm>
#include <cctype>
#include <iomanip>

// ===== HelpFormatter.cpp =====
std::string clap::HelpFormatter::usage_token(const clap::Argument& arg, bool positional) const {
    if (positional) {
        std::string core = "<" + std::string(arg.names()) + ">";
        return arg.is_required() ? core : "[" + core + "]";
    }
    if (!arg.takes_value())
        return "[" + std::string(arg.primary_name()) + "]";

    std::string core = std::string(arg.primary_name()) + " <" + std::string(arg.type_name()) + ">";
    std::string tail = arg.is_multi() ? "..." : "";
    return arg.is_required() ? core + tail : "[" + core + "]" + tail;
}

std::string clap::HelpFormatter::name_col(const clap::Argument& arg) const {
    std::string s = "  " + std::string(arg.names());
    if (arg.is_multi())
        s += "...";
    return s;
}

std::string clap::HelpFormatter::type_col(const clap::Argument& arg) const {
    if (arg.type_name().empty())
        return "";
    return "<" + std::string(arg.type_name()) + ">";
}

std::string clap::HelpFormatter::annotation(const clap::Argument& arg) const {
    if (arg.is_required())
        return " (required)";
    if (!arg.default_str().empty())
        return " (default: " + arg.default_str() + ")";
    return "";
}

size_t clap::HelpFormatter::name_width() const {
    size_t max_w = 0;
    for (const auto& a : _options)
        max_w = std::max(max_w, name_col(*a).size());
    for (const auto& p : _positionals)
        max_w = std::max(max_w, name_col(*p).size());
    return max_w + 2;
}

size_t clap::HelpFormatter::type_width() const {
    size_t max_w = 0;
    for (const auto& a : _options)
        max_w = std::max(max_w, type_col(*a).size());
    for (const auto& p : _positionals)
        max_w = std::max(max_w, type_col(*p).size());
    return max_w + 2;
}

std::string clap::HelpFormatter::usage() const {
    std::ostringstream oss;
    oss << "Usage: " << _name;
    for (const auto& a : _options)
        oss << " " << usage_token(*a, false);
    for (const auto& p : _positionals)
        oss << " " << usage_token(*p, true);
    return oss.str();
}

std::string clap::HelpFormatter::help() const {
    std::ostringstream oss;
    oss << usage() << "\n\n" << _description << "\n";

    const size_t name_w = name_width();
    const size_t type_w = type_width();

    oss << "\nOptions:\n";
    for (const auto& a : _options)
        oss << std::left << std::setw(name_w) << name_col(*a)
            << std::setw(type_w) << type_col(*a)
            << a->description() << annotation(*a) << "\n";

    if (!_positionals.empty()) {
        oss << "\nArguments:\n";
        for (const auto& p : _positionals)
            oss << std::left << std::setw(name_w) << name_col(*p)
                << std::setw(type_w) << type_col(*p)
                << p->description() << annotation(*p) << "\n";
    }
    return oss.str();
}

// ===== App.cpp =====
namespace {
    bool is_long_body(std::string_view body) {
        if (body.empty() || !std::isalnum(static_cast<unsigned char>(body[0])))
            return false;
        for (char c : body)
            if (!std::isalnum(static_cast<unsigned char>(c)) && c != '-' && c != '_')
                return false;
        return true;
    }

    // accepts exactly three formats:
    // -f (single dash, single char)
    // -flag (single dash, long)
    // --flag (double dash, long)
    // Anything else -- --f, spaces, --- is out.
    bool valid_option_name(std::string_view name) {
        if (name.size() < 2 || name[0] != '-')
            return false;
        if (name[1] == '-') {              // double dash: needs a long body
            auto body = name.substr(2);
            return body.size() >= 2 && is_long_body(body);
        }
        auto body = name.substr(1);        // single dash
        if (body.size() == 1)              // short: any char but space or dash
            return body[0] != '-' && !std::isspace(static_cast<unsigned char>(body[0]));
        return is_long_body(body);         // single-dash long
    }
}

clap::App::App(std::string name, std::string description)
    : _name(std::move(name)), _description(std::move(description)) {
}

void clap::App::add_argument(std::unique_ptr<Argument> arg) {
    if (arg->raw_names().empty())
        throw clap::ConfigError(arg->location(),
            "argument registered with no valid name");
    for (const auto& n : arg->raw_names()) {
        if (!valid_option_name(n))
            throw clap::ConfigError(arg->location(),
                "invalid option name '" + n + "' (expected -f, -flag or --flag)");
        for (const auto& existing : _arguments)
            if (existing->matches(n))
                throw clap::ConfigError(arg->location(),
                    "redeclaration of flag " + n, existing->location());
    }
    _arguments.push_back(std::move(arg));
}

clap::Argument* clap::App::find_argument(std::string_view token) {
    for (auto& arg : _arguments)
        if (arg->matches(token)) return arg.get();
    return nullptr;
}

bool clap::App::starts_with(std::string_view str, std::string_view prefix) {
    return str.size() >= prefix.size() &&
        str.compare(0, prefix.size(), prefix) == 0;
}

std::string clap::App::help() const {
    return HelpFormatter(_name, _description, _arguments, _positionals).help();
}

std::string clap::App::usage() const {
    return HelpFormatter(_name, _description, _arguments, _positionals).usage();
}

void clap::App::dispatch(std::string_view token, ArgCursor& cursor) {
    if (_positional_mode || !starts_with(token, "-")) {
        handle_positional(token);
        return;
    }
    size_t dashes = starts_with(token, "--") ? 2 : 1;
    bool discard = token.size() > dashes && token[dashes] == '/';
    std::string clean;
    if (discard) {
        clean = std::string(token.substr(0, dashes)) + std::string(token.substr(dashes + 1));
        token = clean;
    }

    if (starts_with(token, "--") && token.find("=") != std::string_view::npos)
        parse_long_equals(token, discard);
    else if (!starts_with(token, "--") && token.size() > 2)
        parse_short_cluster(token, cursor, discard);
    else
        parse_single(token, cursor, discard);
}

bool clap::App::parse(int argc, char **argv) {
    ArgCursor cursor(argc, argv);
    std::optional<clap::ParseException> failure;

    while (cursor.has_next()) {
        try {
            std::string_view token = cursor.next();
            if (token == "--" && !_positional_mode) {
                _positional_mode = true;
                continue;
            }
            dispatch(token, cursor);
        } catch (const clap::ParseException& e) {
            if (!failure)
                failure = e;
        }
    }

    if (!failure) {
        try {
            check_required();
        } catch (const clap::ParseException& e) {
            failure = e;
        }
    }

    if (failure) {
        _error = "Error: " + std::string(failure->what()) + "\n" + usage() + "\n";
        _error_kind = failure->kind();
        return false;
    }
    _error.clear();
    return true;
}

void clap::App::handle_positional(std::string_view token) {
    if (_positional_idx >= _positionals.size())
        throw clap::UnknownArgument(std::string(token));
    _positionals[_positional_idx++]->parse(token);
}

// --option=value
void clap::App::parse_long_equals(std::string_view token, bool discard) {
    auto eq = token.find('=');
    auto arg_name  = token.substr(0, eq);
    auto arg_value = token.substr(eq + 1);
    auto *arg = find_argument(arg_name);
    if (!arg)
        throw clap::UnknownArgument(std::string(arg_name));
    if (!arg->takes_value())
        throw clap::UnexpectedValue(std::string(arg_name));
    arg->parse(arg_value, discard);
}

// short cluster: -vf, -c10, -c-5, -vc 10
void clap::App::parse_short_cluster(std::string_view token, ArgCursor& cursor, bool discard) {
    for (size_t j = 1; j < token.size(); ++j) {
        std::string short_name{'-', token[j]};
        auto *arg = find_argument(short_name);
        if (!arg)
            throw clap::UnknownArgument(short_name);
        if (arg->takes_value()) {
            auto attached = token.substr(j + 1);
            if (!attached.empty())
                arg->parse(attached, discard);
            else if (cursor.next_is_value())
                arg->parse(cursor.next(), discard);
            else
                throw clap::MissingValue(short_name);
            return;
        }
        arg->parse("", discard);
    }
}

void clap::App::parse_single(std::string_view token, ArgCursor& cursor, bool discard) {
    auto *arg = find_argument(token);
    if (!arg)
        throw clap::UnknownArgument(std::string(token));

    if (arg->takes_value()) {
        if (!cursor.next_is_value())
            throw clap::MissingValue(std::string(token));
        arg->parse(cursor.next(), discard);
    } else {
        arg->parse("", discard);
    }
}

void clap::App::check_required() const {
    for (const auto& arg : _arguments)
        if (arg->is_required() && !arg->is_set())
            throw clap::MissingRequiredArgument(std::string(arg->names()));
    for (const auto& pos : _positionals)
        if (pos->is_required() && !pos->is_set())
            throw clap::MissingRequiredArgument(std::string(pos->names()));
}

#endif // CLAP_IMPLEMENTATION
