#!/usr/bin/env python3
"""amalgamate src/ into a single header file in include/clap.hpp"""

from pathlib import Path
import os
import re

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "include" / "clap.hpp"

# version stamped into the header; release CI overrides via CLAP_VERSION=<tag>
VERSION = os.environ.get("CLAP_VERSION", "dev")

# hardcoded dep order
# could topologically sort the deps but this is easier
HEADER_ORDER = [
    "ClapExceptions.hpp",
    "TypeNames.hpp",
    "Argument.hpp",
    "ArgCursor.hpp",
    "ParseValue.hpp",
    "Flag.hpp",
    "Option.hpp",
    "MultiOption.hpp",
    "Positional.hpp",
    "HelpFormatter.hpp",
    "App.hpp",
]
IMPL_ORDER = [
    "HelpFormatter.cpp",
    "App.cpp",
]

SYS_INC   = re.compile(r'^\s*#\s*include\s*<[^>]+>')     # #inlcude <...>
LOCAL_INC = re.compile(r'^\s*#\s*include\s*"[^"]+"')     # #include "..."
PRAGMA    = re.compile(r'^\s*#\s*pragma\s+once')

def strip_file(name):
    body, includes = [], set()
    for line in (SRC / name).read_text().splitlines():
        if PRAGMA.match(line) or LOCAL_INC.match(line):
              continue
        if SYS_INC.match(line):
            includes.add(line.strip())
            continue
        body.append(line)
    return "\n".join(body).strip("\n"), includes

def gather(order):
    bodies, includes = [], set()
    for name in order:
        b, inc = strip_file(name)
        bodies.append((name, b))
        includes |= inc
    return bodies, includes

hdr_bodies,  hdr_inc  = gather(HEADER_ORDER)
impl_bodies, impl_inc = gather(IMPL_ORDER)
impl_only = impl_inc - hdr_inc

def emit_bodies(bodies):
    return "\n\n".join(f"// ===== {name} =====\n{body}" for name, body in bodies)

out = []
out.append("// ==========================================================================")
out.append("// clap — single-header build. GENERATED by tools/build_single_header.py")
out.append("// DO NOT EDIT. Edit src/ and rerun the script.")
out.append("// ==========================================================================")
out.append("")

out.append("/**")
out.append(" * @file clap.hpp")
out.append(" * @brief CLAP - C++ Command Line Argument Parser")
out.append(" *")
out.append(" * @details")
out.append(" * CLAP is a lightweight, header-only C++ library for parsing command line arguments.")
out.append(" *")
out.append(" * @section Features")
out.append(" * - Flags (e.g. -v, --verbose)")
out.append(" * - Options with values (e.g. -o value, --output=value)")
out.append(" * - Positional arguments (e.g. input files)")
out.append(" * - Multi-value options (e.g. --include=dir1 --include=dir2)")
out.append(" * - Required and optional arguments")
out.append(" * - Default value support")
out.append(" * - Automatic usage and help message generation")
out.append(" *")
out.append(" * @section Usage")
out.append(" * Include this header and use the clap namespace to parse command line arguments.")
out.append(" *")
out.append(" * @author Lucas Pujol")
out.append(f" * @version {VERSION}")
out.append(" */")
out.append("")

out.append("#pragma once")
out.append("")
out.append(f'#define CLAP_VERSION "{VERSION}"')
out.append("")
out += sorted(hdr_inc)
out.append("")
out.append(emit_bodies(hdr_bodies))
out.append("")
out.append("#ifdef CLAP_IMPLEMENTATION")
out.append("")
out += sorted(impl_only)
out.append("")
out.append(emit_bodies(impl_bodies))
out.append("")
out.append("#endif // CLAP_IMPLEMENTATION")
out.append("")

OUT.parent.mkdir(exist_ok=True)
OUT.write_text("\n".join(out))
print(f"wrote {OUT.relative_to(ROOT)}  ({len(hdr_bodies)} headers, {len(impl_bodies)} impl)")